Use Portal_DataSRE
Go

Declare @LastLoadTime DateTime
Set @LastLoadTime = '2013-11-18 17:00:28'
DECLARE @OPENQUERY nvarchar(4000)
Set @OPENQUERY = BC.fnSetOpenQuery('SELECT 
D.PROD_ID, D.PROD_DESC, D.PROD_STTS, 
   D.TRADEMARK_ID, D.TRADEMARK_DESC, D.TRADEMARK_GRP_ID, 
   D.TRADEMARK_GRP_DESC, D.CORE_BRND_GRP_ID, D.CORE_BRND_GRP_DESC, 
   D.CNTNR_TYPE_ID, D.CNTNR_TYPE_DESC, D.PKG_ID, 
   D.PKG_DESC, D.CAFF_CLAIM_ID, D.CAFF_CLAIM_DESC, 
   D.PKG_EXTN_ID, D.PKG_EXTN, D.BEV_TYPE_ID, 
   D.BEV_TYPE_DESC, D.FLVR_ID, D.FLVR_DESC, 
   D.CARB_CODE, D.CARB_CODE_DESC, D.CNTNR_SZ_DESC
FROM CAP_DM.DM_PROD D', 'COP', @LastLoadTime, 'D')
Set @OPENQUERY = Replace(@OpenQuery, 'Select *', 'Select * Into Staging.BCProduct1')
Exec (@OPENQUERY)
Go

Declare @LastLoadTime DateTime
Set @LastLoadTime = '2013-11-18 17:00:28'
DECLARE @OPENQUERY nvarchar(4000)
Set @OPENQUERY = BC.fnSetOpenQuery('SELECT 
D.PROD_ID, 
   D.PKG_TYPE_ID, D.PKG_TYPE_DESC, D.PKG_CFG_ID, 
   D.PKG_CFG_DESC, D.PKG_CAT_DESC, D.PKG_VERSION, 
   D.PCK_VERS_DESC, D.PCK_CONSU_PK_DESC, D.CNSMR_BRND_ID, 
   D.CNSMR_BRND_DESC, D.CAT_SEG_ID, D.CAT_SEG_DESC, 
   D.INIT_CAT_SEG_ID, D.INIT_CAT_SEG_DESC, D.CAL_CLASS_ID, 
   D.CAL_CLASS_DESC, D.BASE_PROD_DESC, D.BS_PR_WEB_PR_FLG, 
   D.VLD_ALL_CHAINS, D.UNITS_IN_PCK, D.PCKS_IN_CASE, 
   D.BASE_PCK_TYPE_DESC, D.PKG_WEB_PRC_FLG, D.STARS_ID, 
   D.NAIS_ID, D.CSTONE_ID, D.PROBE_ID, 
   D.MDM_ID, D.CONV_CASE_CONV_FCTR, D.RELEVANCE_PRC_FLG, 
   D.CS_SLS_RELEVANT_FLG, D.GTIN, D.INFO_PROVIDER_GLN, 
   D.UPC10, D.CNSMR_UPC, D.FRANCHISOR_ID, 
   D.FRANCHISOR_DE, D.PROD_ALIGN_ID, D.PROD_ALIGN_DESC, 
   D.DEL_FLG, 
   D.ROW_MOD_DT, D.PROD_GUID, 
   D.PACK_GRP, D.PACK_GRP_DESC
FROM CAP_DM.DM_PROD D', 'COP', @LastLoadTime, 'D')
Set @OPENQUERY = Replace(@OpenQuery, 'Select *', 'Select * Into Staging.BCProduct2')
Exec (@OPENQUERY)
Go

Create View Staging.BCProduct
As
Select p1.*,    D.PKG_TYPE_ID, D.PKG_TYPE_DESC, D.PKG_CFG_ID, 
   D.PKG_CFG_DESC, D.PKG_CAT_DESC, D.PKG_VERSION, 
   D.PCK_VERS_DESC, D.PCK_CONSU_PK_DESC, D.CNSMR_BRND_ID, 
   D.CNSMR_BRND_DESC, D.CAT_SEG_ID, D.CAT_SEG_DESC, 
   D.INIT_CAT_SEG_ID, D.INIT_CAT_SEG_DESC, D.CAL_CLASS_ID, 
   D.CAL_CLASS_DESC, D.BASE_PROD_DESC, D.BS_PR_WEB_PR_FLG, 
   D.VLD_ALL_CHAINS, D.UNITS_IN_PCK, D.PCKS_IN_CASE, 
   D.BASE_PCK_TYPE_DESC, D.PKG_WEB_PRC_FLG, D.STARS_ID, 
   D.NAIS_ID, D.CSTONE_ID, D.PROBE_ID, 
   D.MDM_ID, D.CONV_CASE_CONV_FCTR, D.RELEVANCE_PRC_FLG, 
   D.CS_SLS_RELEVANT_FLG, D.GTIN, D.INFO_PROVIDER_GLN, 
   D.UPC10, D.CNSMR_UPC, D.FRANCHISOR_ID, 
   D.FRANCHISOR_DE, D.PROD_ALIGN_ID, D.PROD_ALIGN_DESC, 
   D.DEL_FLG, 
   D.ROW_MOD_DT, D.PROD_GUID, 
   D.PACK_GRP, D.PACK_GRP_DESC
From Staging.BCProduct1 p1
Join Staging.BCProduct2 D on p1.PROD_ID = D.PROD_ID
Go

