#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.BC.Model;

namespace DPSG.Portal.BC.Model	
{
	public partial class Channel
	{
		private int _channelID;
		public virtual int ChannelID
		{
			get
			{
				return this._channelID;
			}
			set
			{
				this._channelID = value;
			}
		}
		
		private int? _superChannelID;
		public virtual int? SuperChannelID
		{
			get
			{
				return this._superChannelID;
			}
			set
			{
				this._superChannelID = value;
			}
		}
		
		private string _sAPChannelID;
		public virtual string SAPChannelID
		{
			get
			{
				return this._sAPChannelID;
			}
			set
			{
				this._sAPChannelID = value;
			}
		}
		
		private string _channelName;
		public virtual string ChannelName
		{
			get
			{
				return this._channelName;
			}
			set
			{
				this._channelName = value;
			}
		}
		
		private SuperChannel _superChannel;
		public virtual SuperChannel SuperChannel
		{
			get
			{
				return this._superChannel;
			}
			set
			{
				this._superChannel = value;
			}
		}
		
	}
}
#pragma warning restore 1591
