#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.BC.Model	
{
	public partial class Config
	{
		private int _configID;
		public virtual int ConfigID
		{
			get
			{
				return this._configID;
			}
			set
			{
				this._configID = value;
			}
		}
		
		private string _key;
		public virtual string Key
		{
			get
			{
				return this._key;
			}
			set
			{
				this._key = value;
			}
		}
		
		private string _value;
		public virtual string Value
		{
			get
			{
				return this._value;
			}
			set
			{
				this._value = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private DateTime? _modifiedDate;
		public virtual DateTime? ModifiedDate
		{
			get
			{
				return this._modifiedDate;
			}
			set
			{
				this._modifiedDate = value;
			}
		}
		
		private bool? _sendToMyday;
		public virtual bool? SendToMyday
		{
			get
			{
				return this._sendToMyday;
			}
			set
			{
				this._sendToMyday = value;
			}
		}
		
	}
}
#pragma warning restore 1591
