#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.BC.Model;

namespace DPSG.Portal.BC.Model	
{
	public partial class Country
	{
		private int _countryID;
		public virtual int CountryID
		{
			get
			{
				return this._countryID;
			}
			set
			{
				this._countryID = value;
			}
		}
		
		private string _bCNodeID;
		public virtual string BCNodeID
		{
			get
			{
				return this._bCNodeID;
			}
			set
			{
				this._bCNodeID = value;
			}
		}
		
		private string _countryName;
		public virtual string CountryName
		{
			get
			{
				return this._countryName;
			}
			set
			{
				this._countryName = value;
			}
		}
		
		private int _totalCompanyID;
		public virtual int TotalCompanyID
		{
			get
			{
				return this._totalCompanyID;
			}
			set
			{
				this._totalCompanyID = value;
			}
		}
		
		private bool _active;
		public virtual bool Active
		{
			get
			{
				return this._active;
			}
			set
			{
				this._active = value;
			}
		}
		
		private DateTime _lastModified;
		public virtual DateTime LastModified
		{
			get
			{
				return this._lastModified;
			}
			set
			{
				this._lastModified = value;
			}
		}
		
		private TotalCompany _totalCompany;
		public virtual TotalCompany TotalCompany
		{
			get
			{
				return this._totalCompany;
			}
			set
			{
				this._totalCompany = value;
			}
		}
		
		private IList<System> _systems = new List<System>();
		public virtual IList<System> Systems
		{
			get
			{
				return this._systems;
			}
		}
		
		private IList<BCSalesAccountability> _bCSalesAccountabilities = new List<BCSalesAccountability>();
		public virtual IList<BCSalesAccountability> BCSalesAccountabilities
		{
			get
			{
				return this._bCSalesAccountabilities;
			}
		}
		
	}
}
#pragma warning restore 1591
