#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.BC.Model	
{
	public partial class DisplayLocation
	{
		private int _displayLocationID;
		public virtual int DisplayLocationID
		{
			get
			{
				return this._displayLocationID;
			}
			set
			{
				this._displayLocationID = value;
			}
		}
		
		private string _displayLocationName;
		public virtual string DisplayLocationName
		{
			get
			{
				return this._displayLocationName;
			}
			set
			{
				this._displayLocationName = value;
			}
		}
		
	}
}
#pragma warning restore 1591
