#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.BC.Model;

namespace DPSG.Portal.BC.Model	
{
	public partial class Division
	{
		private int _divisionID;
		public virtual int DivisionID
		{
			get
			{
				return this._divisionID;
			}
			set
			{
				this._divisionID = value;
			}
		}
		
		private string _bCNodeID;
		public virtual string BCNodeID
		{
			get
			{
				return this._bCNodeID;
			}
			set
			{
				this._bCNodeID = value;
			}
		}
		
		private string _divisionName;
		public virtual string DivisionName
		{
			get
			{
				return this._divisionName;
			}
			set
			{
				this._divisionName = value;
			}
		}
		
		private int _zoneID;
		public virtual int ZoneID
		{
			get
			{
				return this._zoneID;
			}
			set
			{
				this._zoneID = value;
			}
		}
		
		private bool _active;
		public virtual bool Active
		{
			get
			{
				return this._active;
			}
			set
			{
				this._active = value;
			}
		}
		
		private DateTime _lastModified;
		public virtual DateTime LastModified
		{
			get
			{
				return this._lastModified;
			}
			set
			{
				this._lastModified = value;
			}
		}
		
		private Zone _zone;
		public virtual Zone Zone
		{
			get
			{
				return this._zone;
			}
			set
			{
				this._zone = value;
			}
		}
		
		private IList<Region> _regions = new List<Region>();
		public virtual IList<Region> Regions
		{
			get
			{
				return this._regions;
			}
		}
		
		private IList<BCSalesAccountability> _bCSalesAccountabilities = new List<BCSalesAccountability>();
		public virtual IList<BCSalesAccountability> BCSalesAccountabilities
		{
			get
			{
				return this._bCSalesAccountabilities;
			}
		}
		
	}
}
#pragma warning restore 1591
