#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.BC.Model;

namespace DPSG.Portal.BC.Model	
{
	public partial class LO
	{
		private int _lOSID;
		public virtual int LOSID
		{
			get
			{
				return this._lOSID;
			}
			set
			{
				this._lOSID = value;
			}
		}
		
		private int _lOSImageID;
		public virtual int LOSImageID
		{
			get
			{
				return this._lOSImageID;
			}
			set
			{
				this._lOSImageID = value;
			}
		}
		
		private string _createdBy;
		public virtual string CreatedBy
		{
			get
			{
				return this._createdBy;
			}
			set
			{
				this._createdBy = value;
			}
		}
		
		private DateTime? _createdDate;
		public virtual DateTime? CreatedDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				this._createdDate = value;
			}
		}
		
		private string _modifiedBy;
		public virtual string ModifiedBy
		{
			get
			{
				return this._modifiedBy;
			}
			set
			{
				this._modifiedBy = value;
			}
		}
		
		private DateTime? _modifiedDate;
		public virtual DateTime? ModifiedDate
		{
			get
			{
				return this._modifiedDate;
			}
			set
			{
				this._modifiedDate = value;
			}
		}
		
		private int? _localChainID;
		public virtual int? LocalChainID
		{
			get
			{
				return this._localChainID;
			}
			set
			{
				this._localChainID = value;
			}
		}
		
		private bool? _isActive;
		public virtual bool? IsActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				this._isActive = value;
			}
		}
		
		private int _channelID;
		public virtual int ChannelID
		{
			get
			{
				return this._channelID;
			}
			set
			{
				this._channelID = value;
			}
		}
		
		private int? _accountID;
		public virtual int? AccountID
		{
			get
			{
				return this._accountID;
			}
			set
			{
				this._accountID = value;
			}
		}
		
		private IList<LOSDisplayLocation> _lOSDisplayLocations = new List<LOSDisplayLocation>();
		public virtual IList<LOSDisplayLocation> LOSDisplayLocations
		{
			get
			{
				return this._lOSDisplayLocations;
			}
		}
		
	}
}
#pragma warning restore 1591
