#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.BC.Model;

namespace DPSG.Portal.BC.Model	
{
	public partial class LOSDisplayLocation
	{
		private int _lOSID;
		public virtual int LOSID
		{
			get
			{
				return this._lOSID;
			}
			set
			{
				this._lOSID = value;
			}
		}
		
		private int _displayLocationID;
		public virtual int DisplayLocationID
		{
			get
			{
				return this._displayLocationID;
			}
			set
			{
				this._displayLocationID = value;
			}
		}
		
		private int? _displaySequence;
		public virtual int? DisplaySequence
		{
			get
			{
				return this._displaySequence;
			}
			set
			{
				this._displaySequence = value;
			}
		}
		
		private int? _gridX;
		public virtual int? GridX
		{
			get
			{
				return this._gridX;
			}
			set
			{
				this._gridX = value;
			}
		}
		
		private int? _gridY;
		public virtual int? GridY
		{
			get
			{
				return this._gridY;
			}
			set
			{
				this._gridY = value;
			}
		}
		
		private int? _isActive;
		public virtual int? IsActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				this._isActive = value;
			}
		}
		
		private string _createdBy;
		public virtual string CreatedBy
		{
			get
			{
				return this._createdBy;
			}
			set
			{
				this._createdBy = value;
			}
		}
		
		private DateTime? _createdDate;
		public virtual DateTime? CreatedDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				this._createdDate = value;
			}
		}
		
		private string _modifiedBy;
		public virtual string ModifiedBy
		{
			get
			{
				return this._modifiedBy;
			}
			set
			{
				this._modifiedBy = value;
			}
		}
		
		private DateTime? _modifiedDate;
		public virtual DateTime? ModifiedDate
		{
			get
			{
				return this._modifiedDate;
			}
			set
			{
				this._modifiedDate = value;
			}
		}
		
		private LO _lO;
		public virtual LO LO
		{
			get
			{
				return this._lO;
			}
			set
			{
				this._lO = value;
			}
		}
		
	}
}
#pragma warning restore 1591
