#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.BC.Model;

namespace DPSG.Portal.BC.Model	
{
	public partial class Region
	{
		private int _regionID;
		public virtual int RegionID
		{
			get
			{
				return this._regionID;
			}
			set
			{
				this._regionID = value;
			}
		}
		
		private string _bCNodeID;
		public virtual string BCNodeID
		{
			get
			{
				return this._bCNodeID;
			}
			set
			{
				this._bCNodeID = value;
			}
		}
		
		private string _regionName;
		public virtual string RegionName
		{
			get
			{
				return this._regionName;
			}
			set
			{
				this._regionName = value;
			}
		}
		
		private int _divisionID;
		public virtual int DivisionID
		{
			get
			{
				return this._divisionID;
			}
			set
			{
				this._divisionID = value;
			}
		}
		
		private string _hierType;
		public virtual string HierType
		{
			get
			{
				return this._hierType;
			}
			set
			{
				this._hierType = value;
			}
		}
		
		private bool _active;
		public virtual bool Active
		{
			get
			{
				return this._active;
			}
			set
			{
				this._active = value;
			}
		}
		
		private DateTime _lastModified;
		public virtual DateTime LastModified
		{
			get
			{
				return this._lastModified;
			}
			set
			{
				this._lastModified = value;
			}
		}
		
		private Division _division;
		public virtual Division Division
		{
			get
			{
				return this._division;
			}
			set
			{
				this._division = value;
			}
		}
		
		private IList<Bottler> _bottlers = new List<Bottler>();
		public virtual IList<Bottler> Bottlers
		{
			get
			{
				return this._bottlers;
			}
		}
		
		private IList<Bottler> _bottlers1 = new List<Bottler>();
		public virtual IList<Bottler> Bottlers1
		{
			get
			{
				return this._bottlers1;
			}
		}
		
		private IList<BCSalesAccountability> _bCSalesAccountabilities = new List<BCSalesAccountability>();
		public virtual IList<BCSalesAccountability> BCSalesAccountabilities
		{
			get
			{
				return this._bCSalesAccountabilities;
			}
		}
		
	}
}
#pragma warning restore 1591
