#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.BC.Model;

namespace DPSG.Portal.BC.Model	
{
	public partial class StoreConditionDisplay
	{
		private int _storeConditionDisplayID;
		public virtual int StoreConditionDisplayID
		{
			get
			{
				return this._storeConditionDisplayID;
			}
			set
			{
				this._storeConditionDisplayID = value;
			}
		}
		
		private int? _storeConditionID;
		public virtual int? StoreConditionID
		{
			get
			{
				return this._storeConditionID;
			}
			set
			{
				this._storeConditionID = value;
			}
		}
		
		private int? _displayLocationID;
		public virtual int? DisplayLocationID
		{
			get
			{
				return this._displayLocationID;
			}
			set
			{
				this._displayLocationID = value;
			}
		}
		
		private int? _promotionID;
		public virtual int? PromotionID
		{
			get
			{
				return this._promotionID;
			}
			set
			{
				this._promotionID = value;
			}
		}
		
		private string _displayLocationNote;
		public virtual string DisplayLocationNote
		{
			get
			{
				return this._displayLocationNote;
			}
			set
			{
				this._displayLocationNote = value;
			}
		}
		
		private int? _displayTypeID;
		public virtual int? DisplayTypeID
		{
			get
			{
				return this._displayTypeID;
			}
			set
			{
				this._displayTypeID = value;
			}
		}
		
		private string _otherNote;
		public virtual string OtherNote
		{
			get
			{
				return this._otherNote;
			}
			set
			{
				this._otherNote = value;
			}
		}
		
		private string _displayImageURL;
		public virtual string DisplayImageURL
		{
			get
			{
				return this._displayImageURL;
			}
			set
			{
				this._displayImageURL = value;
			}
		}
		
		private int? _gridX;
		public virtual int? GridX
		{
			get
			{
				return this._gridX;
			}
			set
			{
				this._gridX = value;
			}
		}
		
		private int? _gridY;
		public virtual int? GridY
		{
			get
			{
				return this._gridY;
			}
			set
			{
				this._gridY = value;
			}
		}
		
		private string _createdBy;
		public virtual string CreatedBy
		{
			get
			{
				return this._createdBy;
			}
			set
			{
				this._createdBy = value;
			}
		}
		
		private DateTime? _createdDate;
		public virtual DateTime? CreatedDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				this._createdDate = value;
			}
		}
		
		private string _modifiedBy;
		public virtual string ModifiedBy
		{
			get
			{
				return this._modifiedBy;
			}
			set
			{
				this._modifiedBy = value;
			}
		}
		
		private DateTime? _modifiedDate;
		public virtual DateTime? ModifiedDate
		{
			get
			{
				return this._modifiedDate;
			}
			set
			{
				this._modifiedDate = value;
			}
		}
		
		private bool? _isActive;
		public virtual bool? IsActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				this._isActive = value;
			}
		}
		
		private int? _clientDisplayID;
		public virtual int? ClientDisplayID
		{
			get
			{
				return this._clientDisplayID;
			}
			set
			{
				this._clientDisplayID = value;
			}
		}
		
		private int? _reasonID;
		public virtual int? ReasonID
		{
			get
			{
				return this._reasonID;
			}
			set
			{
				this._reasonID = value;
			}
		}
		
		private StoreCondition _storeCondition;
		public virtual StoreCondition StoreCondition
		{
			get
			{
				return this._storeCondition;
			}
			set
			{
				this._storeCondition = value;
			}
		}
		
		private DisplayTypeMaster _displayTypeMaster;
		public virtual DisplayTypeMaster DisplayTypeMaster
		{
			get
			{
				return this._displayTypeMaster;
			}
			set
			{
				this._displayTypeMaster = value;
			}
		}
		
		private IList<StoreConditionDisplayDetail> _storeConditionDisplayDetails = new List<StoreConditionDisplayDetail>();
		public virtual IList<StoreConditionDisplayDetail> StoreConditionDisplayDetails
		{
			get
			{
				return this._storeConditionDisplayDetails;
			}
		}
		
	}
}
#pragma warning restore 1591
