#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.BC.Model;

namespace DPSG.Portal.BC.Model	
{
	public partial class StoreConditionDisplayDetail
	{
		private int _storeConditionDisplayID;
		public virtual int StoreConditionDisplayID
		{
			get
			{
				return this._storeConditionDisplayID;
			}
			set
			{
				this._storeConditionDisplayID = value;
			}
		}
		
		private int _systemPackageID;
		public virtual int SystemPackageID
		{
			get
			{
				return this._systemPackageID;
			}
			set
			{
				this._systemPackageID = value;
			}
		}
		
		private int _systemBrandID;
		public virtual int SystemBrandID
		{
			get
			{
				return this._systemBrandID;
			}
			set
			{
				this._systemBrandID = value;
			}
		}
		
		private string _createdBy;
		public virtual string CreatedBy
		{
			get
			{
				return this._createdBy;
			}
			set
			{
				this._createdBy = value;
			}
		}
		
		private DateTime? _createdDate;
		public virtual DateTime? CreatedDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				this._createdDate = value;
			}
		}
		
		private string _modifiedBy;
		public virtual string ModifiedBy
		{
			get
			{
				return this._modifiedBy;
			}
			set
			{
				this._modifiedBy = value;
			}
		}
		
		private DateTime? _modifiedDate;
		public virtual DateTime? ModifiedDate
		{
			get
			{
				return this._modifiedDate;
			}
			set
			{
				this._modifiedDate = value;
			}
		}
		
		private bool? _isActive;
		public virtual bool? IsActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				this._isActive = value;
			}
		}
		
		private int _storeConditionDisplayDetailID;
		public virtual int StoreConditionDisplayDetailID
		{
			get
			{
				return this._storeConditionDisplayDetailID;
			}
			set
			{
				this._storeConditionDisplayDetailID = value;
			}
		}
		
		private StoreConditionDisplay _storeConditionDisplay;
		public virtual StoreConditionDisplay StoreConditionDisplay
		{
			get
			{
				return this._storeConditionDisplay;
			}
			set
			{
				this._storeConditionDisplay = value;
			}
		}
		
	}
}
#pragma warning restore 1591
