#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.BC.Model	
{
	public partial class StoreTieInRate
	{
		private int _storeConditionID;
		public virtual int StoreConditionID
		{
			get
			{
				return this._storeConditionID;
			}
			set
			{
				this._storeConditionID = value;
			}
		}
		
		private int _systemBrandId;
		public virtual int SystemBrandId
		{
			get
			{
				return this._systemBrandId;
			}
			set
			{
				this._systemBrandId = value;
			}
		}
		
		private int _tieInRate;
		public virtual int TieInRate
		{
			get
			{
				return this._tieInRate;
			}
			set
			{
				this._tieInRate = value;
			}
		}
		
		private bool? _isActive;
		public virtual bool? IsActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				this._isActive = value;
			}
		}
		
		private string _createdBy;
		public virtual string CreatedBy
		{
			get
			{
				return this._createdBy;
			}
			set
			{
				this._createdBy = value;
			}
		}
		
		private DateTime? _createdDate;
		public virtual DateTime? CreatedDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				this._createdDate = value;
			}
		}
		
		private string _modifiedBy;
		public virtual string ModifiedBy
		{
			get
			{
				return this._modifiedBy;
			}
			set
			{
				this._modifiedBy = value;
			}
		}
		
		private DateTime? _modifiedDate;
		public virtual DateTime? ModifiedDate
		{
			get
			{
				return this._modifiedDate;
			}
			set
			{
				this._modifiedDate = value;
			}
		}
		
		private int? _totalDisplays;
		public virtual int? TotalDisplays
		{
			get
			{
				return this._totalDisplays;
			}
			set
			{
				this._totalDisplays = value;
			}
		}
		
	}
}
#pragma warning restore 1591
