#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.BC.Model;

namespace DPSG.Portal.BC.Model	
{
	public partial class SuperChannel
	{
		private int _superChannelID;
		public virtual int SuperChannelID
		{
			get
			{
				return this._superChannelID;
			}
			set
			{
				this._superChannelID = value;
			}
		}
		
		private string _sAPSuperChannelID;
		public virtual string SAPSuperChannelID
		{
			get
			{
				return this._sAPSuperChannelID;
			}
			set
			{
				this._sAPSuperChannelID = value;
			}
		}
		
		private string _superChannelName;
		public virtual string SuperChannelName
		{
			get
			{
				return this._superChannelName;
			}
			set
			{
				this._superChannelName = value;
			}
		}
		
		private Char _format;
		public virtual Char Format
		{
			get
			{
				return this._format;
			}
			set
			{
				this._format = value;
			}
		}
		
		private IList<Channel> _channels = new List<Channel>();
		public virtual IList<Channel> Channels
		{
			get
			{
				return this._channels;
			}
		}
		
	}
}
#pragma warning restore 1591
