#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.BC.Model;

namespace DPSG.Portal.BC.Model	
{
	public partial class SystemPickList
	{
		private int _bCSystemID;
		public virtual int BCSystemID
		{
			get
			{
				return this._bCSystemID;
			}
			set
			{
				this._bCSystemID = value;
			}
		}
		
		private int _pickListID;
		public virtual int PickListID
		{
			get
			{
				return this._pickListID;
			}
			set
			{
				this._pickListID = value;
			}
		}
		
		private PickList _pickList;
		public virtual PickList PickList
		{
			get
			{
				return this._pickList;
			}
			set
			{
				this._pickList = value;
			}
		}
		
	}
}
#pragma warning restore 1591
