#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.BC.Model;

namespace DPSG.Portal.BC.Model	
{
	public partial class System
	{
		private int _systemID;
		public virtual int SystemID
		{
			get
			{
				return this._systemID;
			}
			set
			{
				this._systemID = value;
			}
		}
		
		private string _bCNodeID;
		public virtual string BCNodeID
		{
			get
			{
				return this._bCNodeID;
			}
			set
			{
				this._bCNodeID = value;
			}
		}
		
		private string _systemName;
		public virtual string SystemName
		{
			get
			{
				return this._systemName;
			}
			set
			{
				this._systemName = value;
			}
		}
		
		private int _countryID;
		public virtual int CountryID
		{
			get
			{
				return this._countryID;
			}
			set
			{
				this._countryID = value;
			}
		}
		
		private bool _active;
		public virtual bool Active
		{
			get
			{
				return this._active;
			}
			set
			{
				this._active = value;
			}
		}
		
		private DateTime _lastModified;
		public virtual DateTime LastModified
		{
			get
			{
				return this._lastModified;
			}
			set
			{
				this._lastModified = value;
			}
		}
		
		private Country _country;
		public virtual Country Country
		{
			get
			{
				return this._country;
			}
			set
			{
				this._country = value;
			}
		}
		
		private IList<Zone> _zones = new List<Zone>();
		public virtual IList<Zone> Zones
		{
			get
			{
				return this._zones;
			}
		}
		
		private IList<BCSalesAccountability> _bCSalesAccountabilities = new List<BCSalesAccountability>();
		public virtual IList<BCSalesAccountability> BCSalesAccountabilities
		{
			get
			{
				return this._bCSalesAccountabilities;
			}
		}
		
	}
}
#pragma warning restore 1591
