#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.BC.Model	
{
	public partial class SystemTradeMark
	{
		private int _systemTradeMarkID;
		public virtual int SystemTradeMarkID
		{
			get
			{
				return this._systemTradeMarkID;
			}
			set
			{
				this._systemTradeMarkID = value;
			}
		}
		
		private string _externalTradeMarkName;
		public virtual string ExternalTradeMarkName
		{
			get
			{
				return this._externalTradeMarkName;
			}
			set
			{
				this._externalTradeMarkName = value;
			}
		}
		
		private int? _tradeMarkID;
		public virtual int? TradeMarkID
		{
			get
			{
				return this._tradeMarkID;
			}
			set
			{
				this._tradeMarkID = value;
			}
		}
		
		private int? _imageID;
		public virtual int? ImageID
		{
			get
			{
				return this._imageID;
			}
			set
			{
				this._imageID = value;
			}
		}
		
		private int? _tradeMarkLevelSort;
		public virtual int? TradeMarkLevelSort
		{
			get
			{
				return this._tradeMarkLevelSort;
			}
			set
			{
				this._tradeMarkLevelSort = value;
			}
		}
		
		private bool? _isActive;
		public virtual bool? IsActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				this._isActive = value;
			}
		}
		
		private string _createdBy;
		public virtual string CreatedBy
		{
			get
			{
				return this._createdBy;
			}
			set
			{
				this._createdBy = value;
			}
		}
		
		private DateTime? _createdDate;
		public virtual DateTime? CreatedDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				this._createdDate = value;
			}
		}
		
		private string _modifiedBy;
		public virtual string ModifiedBy
		{
			get
			{
				return this._modifiedBy;
			}
			set
			{
				this._modifiedBy = value;
			}
		}
		
		private DateTime? _modifiedDate;
		public virtual DateTime? ModifiedDate
		{
			get
			{
				return this._modifiedDate;
			}
			set
			{
				this._modifiedDate = value;
			}
		}
		
	}
}
#pragma warning restore 1591
