#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.BC.Model	
{
	public partial class SystemPackage
	{
		private int _systemPackageID;
		public virtual int SystemPackageID
		{
			get
			{
				return this._systemPackageID;
			}
			set
			{
				this._systemPackageID = value;
			}
		}
		
		private int? _packageConfigID;
		public virtual int? PackageConfigID
		{
			get
			{
				return this._packageConfigID;
			}
			set
			{
				this._packageConfigID = value;
			}
		}
		
		private int? _bCSystemID;
		public virtual int? BCSystemID
		{
			get
			{
				return this._bCSystemID;
			}
			set
			{
				this._bCSystemID = value;
			}
		}
		
		private int? _packageLevelSort;
		public virtual int? PackageLevelSort
		{
			get
			{
				return this._packageLevelSort;
			}
			set
			{
				this._packageLevelSort = value;
			}
		}
		
		private bool? _isActive;
		public virtual bool? IsActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				this._isActive = value;
			}
		}
		
		private string _createdBy;
		public virtual string CreatedBy
		{
			get
			{
				return this._createdBy;
			}
			set
			{
				this._createdBy = value;
			}
		}
		
		private DateTime? _createdDate;
		public virtual DateTime? CreatedDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				this._createdDate = value;
			}
		}
		
		private string _modifiedBy;
		public virtual string ModifiedBy
		{
			get
			{
				return this._modifiedBy;
			}
			set
			{
				this._modifiedBy = value;
			}
		}
		
		private DateTime? _modifiedDate;
		public virtual DateTime? ModifiedDate
		{
			get
			{
				return this._modifiedDate;
			}
			set
			{
				this._modifiedDate = value;
			}
		}
		
		private string _containerType;
		public virtual string ContainerType
		{
			get
			{
				return this._containerType;
			}
			set
			{
				this._containerType = value;
			}
		}
		
		private string _packageName;
		public virtual string PackageName
		{
			get
			{
				return this._packageName;
			}
			set
			{
				this._packageName = value;
			}
		}
		
	}
}
#pragma warning restore 1591
