#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.BC.Model;

namespace DPSG.Portal.BC.Model	
{
	public partial class TBottlerTrademark
	{
		private int _territoryTypeID;
		public virtual int TerritoryTypeID
		{
			get
			{
				return this._territoryTypeID;
			}
			set
			{
				this._territoryTypeID = value;
			}
		}
		
		private int _productTypeID;
		public virtual int ProductTypeID
		{
			get
			{
				return this._productTypeID;
			}
			set
			{
				this._productTypeID = value;
			}
		}
		
		private int _bottlerID;
		public virtual int BottlerID
		{
			get
			{
				return this._bottlerID;
			}
			set
			{
				this._bottlerID = value;
			}
		}
		
		private long _bCBottlerID;
		public virtual long BCBottlerID
		{
			get
			{
				return this._bCBottlerID;
			}
			set
			{
				this._bCBottlerID = value;
			}
		}
		
		private string _bottlerName;
		public virtual string BottlerName
		{
			get
			{
				return this._bottlerName;
			}
			set
			{
				this._bottlerName = value;
			}
		}
		
		private int _tradeMarkID;
		public virtual int TradeMarkID
		{
			get
			{
				return this._tradeMarkID;
			}
			set
			{
				this._tradeMarkID = value;
			}
		}
		
		private string _sAPTradeMarkID;
		public virtual string SAPTradeMarkID
		{
			get
			{
				return this._sAPTradeMarkID;
			}
			set
			{
				this._sAPTradeMarkID = value;
			}
		}
		
		private string _tradeMarkName;
		public virtual string TradeMarkName
		{
			get
			{
				return this._tradeMarkName;
			}
			set
			{
				this._tradeMarkName = value;
			}
		}
		
		private DateTime _lastModified;
		public virtual DateTime LastModified
		{
			get
			{
				return this._lastModified;
			}
			set
			{
				this._lastModified = value;
			}
		}
		
		private Bottler _bottler;
		public virtual Bottler Bottler
		{
			get
			{
				return this._bottler;
			}
			set
			{
				this._bottler = value;
			}
		}
		
	}
}
#pragma warning restore 1591
