#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.BC.Model;

namespace DPSG.Portal.BC.Model	
{
	public partial class Zone
	{
		private int _zoneID;
		public virtual int ZoneID
		{
			get
			{
				return this._zoneID;
			}
			set
			{
				this._zoneID = value;
			}
		}
		
		private string _bCNodeID;
		public virtual string BCNodeID
		{
			get
			{
				return this._bCNodeID;
			}
			set
			{
				this._bCNodeID = value;
			}
		}
		
		private string _zoneName;
		public virtual string ZoneName
		{
			get
			{
				return this._zoneName;
			}
			set
			{
				this._zoneName = value;
			}
		}
		
		private int _systemID;
		public virtual int SystemID
		{
			get
			{
				return this._systemID;
			}
			set
			{
				this._systemID = value;
			}
		}
		
		private bool _active;
		public virtual bool Active
		{
			get
			{
				return this._active;
			}
			set
			{
				this._active = value;
			}
		}
		
		private DateTime _lastModified;
		public virtual DateTime LastModified
		{
			get
			{
				return this._lastModified;
			}
			set
			{
				this._lastModified = value;
			}
		}
		
		private System _system;
		public virtual System System
		{
			get
			{
				return this._system;
			}
			set
			{
				this._system = value;
			}
		}
		
		private IList<Division> _divisions = new List<Division>();
		public virtual IList<Division> Divisions
		{
			get
			{
				return this._divisions;
			}
		}
		
		private IList<BCSalesAccountability> _bCSalesAccountabilities = new List<BCSalesAccountability>();
		public virtual IList<BCSalesAccountability> BCSalesAccountabilities
		{
			get
			{
				return this._bCSalesAccountabilities;
			}
		}
		
	}
}
#pragma warning restore 1591
