<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="SDMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=vh-portal1;Integrated Security=True" SettingsObjectName="DPSG.Portal.BottlerMappingCalculator.Properties.Settings" SettingsPropertyName="DataSourceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="BC.tBottlerAccountLocation" Member="tBottlerAccountLocations">
    <Type Name="tBottlerAccountLocation">
      <Column Name="TerritoryTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BottlerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TradeMarkID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccountID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="AccountCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="BC.tBottlerTerritoryMap" Member="tBottlerTerritoryMaps">
    <Type Name="tBottlerTerritoryMap">
      <Column Name="TerritoryTypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BottlerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TradeMarkID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Sequence" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(10,6) NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(10,6) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="BC.vBottlerTerritoryMapHeader" Member="vBottlerTerritoryMapHeaders">
    <Type Name="vBottlerTerritoryMapHeader">
      <Column Name="TerritoryTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BottlerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TradeMarkID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>