#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPSG.Portal.BottlerMappingCalculator
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataSource")]
	public partial class SDMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttBottlerTerritoryMap(tBottlerTerritoryMap instance);
    partial void UpdatetBottlerTerritoryMap(tBottlerTerritoryMap instance);
    partial void DeletetBottlerTerritoryMap(tBottlerTerritoryMap instance);
    #endregion
		
		public SDMDataContext() : 
				base(global::DPSG.Portal.BottlerMappingCalculator.Properties.Settings.Default.DataSourceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SDMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SDMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SDMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SDMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tBottlerAccountLocation> tBottlerAccountLocations
		{
			get
			{
				return this.GetTable<tBottlerAccountLocation>();
			}
		}
		
		public System.Data.Linq.Table<tBottlerTerritoryMap> tBottlerTerritoryMaps
		{
			get
			{
				return this.GetTable<tBottlerTerritoryMap>();
			}
		}
		
		public System.Data.Linq.Table<vBottlerTerritoryMapHeader> vBottlerTerritoryMapHeaders
		{
			get
			{
				return this.GetTable<vBottlerTerritoryMapHeader>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="BC.tBottlerAccountLocation")]
	public partial class tBottlerAccountLocation
	{
		
		private int _TerritoryTypeID;
		
		private int _BottlerID;
		
		private int _TradeMarkID;
		
		private System.Nullable<int> _AccountID;
		
		private System.Nullable<decimal> _Latitude;
		
		private System.Nullable<decimal> _Longitude;
		
		private System.Nullable<int> _AccountCount;
		
		public tBottlerAccountLocation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerritoryTypeID", DbType="Int NOT NULL")]
		public int TerritoryTypeID
		{
			get
			{
				return this._TerritoryTypeID;
			}
			set
			{
				if ((this._TerritoryTypeID != value))
				{
					this._TerritoryTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BottlerID", DbType="Int NOT NULL")]
		public int BottlerID
		{
			get
			{
				return this._BottlerID;
			}
			set
			{
				if ((this._BottlerID != value))
				{
					this._BottlerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TradeMarkID", DbType="Int NOT NULL")]
		public int TradeMarkID
		{
			get
			{
				return this._TradeMarkID;
			}
			set
			{
				if ((this._TradeMarkID != value))
				{
					this._TradeMarkID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", DbType="Int")]
		public System.Nullable<int> AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					this._AccountID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this._Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this._Longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountCount", DbType="Int")]
		public System.Nullable<int> AccountCount
		{
			get
			{
				return this._AccountCount;
			}
			set
			{
				if ((this._AccountCount != value))
				{
					this._AccountCount = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="BC.tBottlerTerritoryMap")]
	public partial class tBottlerTerritoryMap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TerritoryTypeID;
		
		private int _BottlerID;
		
		private int _TradeMarkID;
		
		private int _Sequence;
		
		private decimal _Latitude;
		
		private decimal _Longitude;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTerritoryTypeIDChanging(int value);
    partial void OnTerritoryTypeIDChanged();
    partial void OnBottlerIDChanging(int value);
    partial void OnBottlerIDChanged();
    partial void OnTradeMarkIDChanging(int value);
    partial void OnTradeMarkIDChanged();
    partial void OnSequenceChanging(int value);
    partial void OnSequenceChanged();
    partial void OnLatitudeChanging(decimal value);
    partial void OnLatitudeChanged();
    partial void OnLongitudeChanging(decimal value);
    partial void OnLongitudeChanged();
    #endregion
		
		public tBottlerTerritoryMap()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerritoryTypeID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TerritoryTypeID
		{
			get
			{
				return this._TerritoryTypeID;
			}
			set
			{
				if ((this._TerritoryTypeID != value))
				{
					this.OnTerritoryTypeIDChanging(value);
					this.SendPropertyChanging();
					this._TerritoryTypeID = value;
					this.SendPropertyChanged("TerritoryTypeID");
					this.OnTerritoryTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BottlerID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int BottlerID
		{
			get
			{
				return this._BottlerID;
			}
			set
			{
				if ((this._BottlerID != value))
				{
					this.OnBottlerIDChanging(value);
					this.SendPropertyChanging();
					this._BottlerID = value;
					this.SendPropertyChanged("BottlerID");
					this.OnBottlerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TradeMarkID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TradeMarkID
		{
			get
			{
				return this._TradeMarkID;
			}
			set
			{
				if ((this._TradeMarkID != value))
				{
					this.OnTradeMarkIDChanging(value);
					this.SendPropertyChanging();
					this._TradeMarkID = value;
					this.SendPropertyChanged("TradeMarkID");
					this.OnTradeMarkIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sequence", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Sequence
		{
			get
			{
				return this._Sequence;
			}
			set
			{
				if ((this._Sequence != value))
				{
					this.OnSequenceChanging(value);
					this.SendPropertyChanging();
					this._Sequence = value;
					this.SendPropertyChanged("Sequence");
					this.OnSequenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Decimal(10,6) NOT NULL")]
		public decimal Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Decimal(10,6) NOT NULL")]
		public decimal Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this.OnLongitudeChanging(value);
					this.SendPropertyChanging();
					this._Longitude = value;
					this.SendPropertyChanged("Longitude");
					this.OnLongitudeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="BC.vBottlerTerritoryMapHeader")]
	public partial class vBottlerTerritoryMapHeader
	{
		
		private int _TerritoryTypeID;
		
		private int _BottlerID;
		
		private int _TradeMarkID;
		
		public vBottlerTerritoryMapHeader()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerritoryTypeID", DbType="Int NOT NULL")]
		public int TerritoryTypeID
		{
			get
			{
				return this._TerritoryTypeID;
			}
			set
			{
				if ((this._TerritoryTypeID != value))
				{
					this._TerritoryTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BottlerID", DbType="Int NOT NULL")]
		public int BottlerID
		{
			get
			{
				return this._BottlerID;
			}
			set
			{
				if ((this._BottlerID != value))
				{
					this._BottlerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TradeMarkID", DbType="Int NOT NULL")]
		public int TradeMarkID
		{
			get
			{
				return this._TradeMarkID;
			}
			set
			{
				if ((this._TradeMarkID != value))
				{
					this._TradeMarkID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
