#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.Security;


namespace DPSG.Portal.Framework.Security	
{
	public partial class ApplicationEntity
	{
		private int _entityID;
		public virtual int EntityID 
		{ 
		    get
		    {
		        return this._entityID;
		    }
		    set
		    {
		        this._entityID = value;
		    }
		}
		
		private string _entityName;
		public virtual string EntityName 
		{ 
		    get
		    {
		        return this._entityName;
		    }
		    set
		    {
		        this._entityName = value;
		    }
		}
		
		private int _appID;
		public virtual int AppID 
		{ 
		    get
		    {
		        return this._appID;
		    }
		    set
		    {
		        this._appID = value;
		    }
		}
		
		private Application _application;
		public virtual Application Application 
		{ 
		    get
		    {
		        return this._application;
		    }
		    set
		    {
		        this._application = value;
		    }
		}
		
		private IList<UserPermission> _userPermissions = new List<UserPermission>();
		public virtual IList<UserPermission> UserPermissions 
		{ 
		    get
		    {
		        return this._userPermissions;
		    }
		}
		
		private IList<RolePermission> _rolePermissions = new List<RolePermission>();
		public virtual IList<RolePermission> RolePermissions 
		{ 
		    get
		    {
		        return this._rolePermissions;
		    }
		}
		
	}
}
