#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.Security;


namespace DPSG.Portal.Framework.Security	
{
	public partial class Application
	{
		private int _appID;
		public virtual int AppID 
		{ 
		    get
		    {
		        return this._appID;
		    }
		    set
		    {
		        this._appID = value;
		    }
		}
		
		private string _appName;
		public virtual string AppName 
		{ 
		    get
		    {
		        return this._appName;
		    }
		    set
		    {
		        this._appName = value;
		    }
		}
		
		private IList<ApplicationEntity> _applicationEntities = new List<ApplicationEntity>();
		public virtual IList<ApplicationEntity> ApplicationEntities 
		{ 
		    get
		    {
		        return this._applicationEntities;
		    }
		}
		
	}
}
