#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace DPSG.Portal.Framework.Security	
{
	public partial class UserNationalChain
	{
		private string _gSN;
		public virtual string GSN 
		{ 
		    get
		    {
		        return this._gSN;
		    }
		    set
		    {
		        this._gSN = value;
		    }
		}
		
		private int? _nationalChainID;
		public virtual int? NationalChainID 
		{ 
		    get
		    {
		        return this._nationalChainID;
		    }
		    set
		    {
		        this._nationalChainID = value;
		    }
		}
		
		private bool? _isAdmin;
		public virtual bool? IsAdmin 
		{ 
		    get
		    {
		        return this._isAdmin;
		    }
		    set
		    {
		        this._isAdmin = value;
		    }
		}
		
		private int _userNationalChainId;
		public virtual int UserNationalChainId 
		{ 
		    get
		    {
		        return this._userNationalChainId;
		    }
		    set
		    {
		        this._userNationalChainId = value;
		    }
		}
		
	}
}
