Use Portal_Data
Go

--- LRB ---
/*
What does this mean: 
*/


-- VDPSGLRB_MKTTAB --
-- ---------------------------------- Markets?
-- Multiple entities stored in the same structure?
SELECT * 
FROM MOTTS01..CSA12AXI.VDPSGLRB_MKTTAB -- Is this the SAP Chain?
Go

SELECT Count(MRKT_KEY) 
FROM MOTTS01..CSA12AXI.VDPSGLRB_MKTTAB
Go

-------------------------------------
-- VDPSGLRB_PRODTAB ----------------- Products?
SELECT Top 100 * 
FROM MOTTS01..CSA12AXI.VDPSGLRB_PRODTAB -- Is this the SAP Materials
Go

SELECT Count(PRDC_KEY) FROM MOTTS01..CSA12AXI.VDPSGLRB_PRODTAB
Go

-------------------------------------
-- V_PERTABTTLLRB ------------------- Periods?
SELECT NUM_OF_WKS, PRD_DET_LVL, PRD_DSC_LONG, PRD_DSC_SHORT, PRD_DSP_ORD, PRD_KEY, PRD_TAG, WK_ENDING_DT, 
       PRD_LVL_TYP, SYND_CLND_MTH, SYND_CLND_QTR_NUM, SYND_CLND_WK_NUM, SYND_CLND_YR, SYND_QTR_DSC, SYND_CLND_MTH_YR, SYND_CLND_WK_YR, SYND_CLND_QTR, SYND_MTH_DSC, SYND_CLND_MTH_NUM,
'' AS "CUSTOM"
FROM MOTTS01..CSA12AXI.PERTAB

---  BSCFFSTTTLLRB ---
SELECT Top 100 PRD_KEY, MRKT_KEY, PRDC_KEY, UNITS, UNITSEQ, DOL, PUNITS, PSS, CUMPSS, BUNITS, BUNITSEQ, BDOL,SPMDOL  
FROM MOTTS01..CSA12AXI.V_BASICFCT 
WHERE PRDC_KEY IN (SELECT PRDC_KEY FROM MOTTS01..CSA12AXI.VDPSGLRB_PRODTAB)
Go

---  BSCFSEDTTLLRB ---
SELECT Top 100 PRD_KEY, MRKT_KEY, PRDC_KEY, PEQ, ACVSELL, CUMACVSELL, ACV, SPMU, SPMEQ  
FROM MOTTS01..CSA12AXI.V_BASICFCT 
WHERE PRDC_KEY IN (SELECT PRDC_KEY FROM MOTTS01..CSA12AXI.VDPSGLRB_PRODTAB)
Go

