use Portal_Data
Go

-- Schema is CSAFSUPI
/*
Market
CSAFSUPI.VDPSGSAUCE_MKTTAB
	What about market detail level:
	market
	corpoorate child
	trading area
	corporate total
	channel

Product?
CSAFSUPI.VDPSGSAUCE_PRODTAB
Columns Key, DSC_L, DSC_S, Tag, level?

Period PERTABSAUCE:
CSAFSUPI.PERTAB


*/

--Some Fact
--CSAFSUPI.BSCFFTSAUCE
SELECT PRD_KEY, MRKT_KEY, PRDC_KEY, UNITS, UNITSEQ, DOL, PUNITS, PSS, CUMPSS, BUNITS, BUNITSEQ, BDOL,SPMDOL  
FROM CSAFSUPI.V_BASICFCT 
WHERE PRDC_KEY IN (SELECT PRDC_KEY FROM CSAFSUPI.VDPSGSAUCE_PRODTAB)

--BSCFSEDSAUCE
SELECT PRD_KEY, MRKT_KEY, PRDC_KEY, PEQ, ACVSELL, CUMACVSELL, ACV, SPMU, SPMEQ  
FROM CSAFSUPI.V_BASICFCT 
WHERE PRDC_KEY IN (SELECT PRDC_KEY FROM CSAFSUPI.VDPSGSAUCE_PRODTAB)

