#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class AlertNotificationLastAccessDatetime
	{
		private long _alertNotificationId;
		public virtual long AlertNotificationId
		{
			get
			{
				return this._alertNotificationId;
			}
			set
			{
				this._alertNotificationId = value;
			}
		}
		
		private string _gSN;
		public virtual string GSN
		{
			get
			{
				return this._gSN;
			}
			set
			{
				this._gSN = value;
			}
		}
		
		private string _key;
		public virtual string Key
		{
			get
			{
				return this._key;
			}
			set
			{
				this._key = value;
			}
		}
		
		private DateTime? _lastAccessDateTime;
		public virtual DateTime? LastAccessDateTime
		{
			get
			{
				return this._lastAccessDateTime;
			}
			set
			{
				this._lastAccessDateTime = value;
			}
		}
		
	}
}
#pragma warning restore 1591
