#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class Bcsalesaccountability
	{
		private int _bCSalesAccountabilityID;
		public virtual int BCSalesAccountabilityID
		{
			get
			{
				return this._bCSalesAccountabilityID;
			}
			set
			{
				this._bCSalesAccountabilityID = value;
			}
		}
		
		private string _gSN;
		public virtual string GSN
		{
			get
			{
				return this._gSN;
			}
			set
			{
				this._gSN = value;
			}
		}
		
		private int? _totalCompanyID;
		public virtual int? TotalCompanyID
		{
			get
			{
				return this._totalCompanyID;
			}
			set
			{
				this._totalCompanyID = value;
			}
		}
		
		private int? _countryID;
		public virtual int? CountryID
		{
			get
			{
				return this._countryID;
			}
			set
			{
				this._countryID = value;
			}
		}
		
		private int? _systemID;
		public virtual int? SystemID
		{
			get
			{
				return this._systemID;
			}
			set
			{
				this._systemID = value;
			}
		}
		
		private int? _zoneID;
		public virtual int? ZoneID
		{
			get
			{
				return this._zoneID;
			}
			set
			{
				this._zoneID = value;
			}
		}
		
		private int? _divisionID;
		public virtual int? DivisionID
		{
			get
			{
				return this._divisionID;
			}
			set
			{
				this._divisionID = value;
			}
		}
		
		private int? _regionID;
		public virtual int? RegionID
		{
			get
			{
				return this._regionID;
			}
			set
			{
				this._regionID = value;
			}
		}
		
		private bool _isPrimary;
		public virtual bool IsPrimary
		{
			get
			{
				return this._isPrimary;
			}
			set
			{
				this._isPrimary = value;
			}
		}
		
		private bool _isSystemLoad;
		public virtual bool IsSystemLoad
		{
			get
			{
				return this._isSystemLoad;
			}
			set
			{
				this._isSystemLoad = value;
			}
		}
		
		private DateTime _lastModified;
		public virtual DateTime LastModified
		{
			get
			{
				return this._lastModified;
			}
			set
			{
				this._lastModified = value;
			}
		}
		
	}
}
#pragma warning restore 1591
