#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.SDM;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class Brand
	{
		private int _brandID;
		public virtual int BrandID
		{
			get
			{
				return this._brandID;
			}
			set
			{
				this._brandID = value;
			}
		}
		
		private int _trademarkID;
		public virtual int TrademarkID
		{
			get
			{
				return this._trademarkID;
			}
			set
			{
				this._trademarkID = value;
			}
		}
		
		private string _sAPBrandID;
		public virtual string SAPBrandID
		{
			get
			{
				return this._sAPBrandID;
			}
			set
			{
				this._sAPBrandID = value;
			}
		}
		
		private string _brandName;
		public virtual string BrandName
		{
			get
			{
				return this._brandName;
			}
			set
			{
				this._brandName = value;
			}
		}
		
		private string _sPBrandName;
		public virtual string SPBrandName
		{
			get
			{
				return this._sPBrandName;
			}
			set
			{
				this._sPBrandName = value;
			}
		}
		
		private IList<Material> _materials = new List<Material>();
		public virtual IList<Material> Materials
		{
			get
			{
				return this._materials;
			}
		}
		
	}
}
#pragma warning restore 1591
