#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.SDM;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class Branch
	{
		private string _zipCode;
		public virtual string ZipCode
		{
			get
			{
				return this._zipCode;
			}
			set
			{
				this._zipCode = value;
			}
		}
		
		private string _sPBranchName;
		public virtual string SPBranchName
		{
			get
			{
				return this._sPBranchName;
			}
			set
			{
				this._sPBranchName = value;
			}
		}
		
		private string _sAPBranchID;
		public virtual string SAPBranchID
		{
			get
			{
				return this._sAPBranchID;
			}
			set
			{
				this._sAPBranchID = value;
			}
		}
		
		private int? _rMLocationID;
		public virtual int? RMLocationID
		{
			get
			{
				return this._rMLocationID;
			}
			set
			{
				this._rMLocationID = value;
			}
		}
		
		private string _rMLocationCity;
		public virtual string RMLocationCity
		{
			get
			{
				return this._rMLocationCity;
			}
			set
			{
				this._rMLocationCity = value;
			}
		}
		
		private DateTime? _lastModified;
		public virtual DateTime? LastModified
		{
			get
			{
				return this._lastModified;
			}
			set
			{
				this._lastModified = value;
			}
		}
		
		private int? _changeTrackNumber;
		public virtual int? ChangeTrackNumber
		{
			get
			{
				return this._changeTrackNumber;
			}
			set
			{
				this._changeTrackNumber = value;
			}
		}
		
		private string _branchName;
		public virtual string BranchName
		{
			get
			{
				return this._branchName;
			}
			set
			{
				this._branchName = value;
			}
		}
		
		private int _branchID;
		public virtual int BranchID
		{
			get
			{
				return this._branchID;
			}
			set
			{
				this._branchID = value;
			}
		}
		
		private bool? _active;
		public virtual bool? Active
		{
			get
			{
				return this._active;
			}
			set
			{
				this._active = value;
			}
		}
		
		private bool? _mySplashNetEnabled;
		public virtual bool? MySplashNetEnabled
		{
			get
			{
				return this._mySplashNetEnabled;
			}
			set
			{
				this._mySplashNetEnabled = value;
			}
		}
		
		private int? _areaID;
		public virtual int? AreaID
		{
			get
			{
				return this._areaID;
			}
			set
			{
				this._areaID = value;
			}
		}
		
		private Area _area;
		public virtual Area Area
		{
			get
			{
				return this._area;
			}
			set
			{
				this._area = value;
			}
		}
		
		private IList<DimBranchPlan> _dimBranchPlans = new List<DimBranchPlan>();
		public virtual IList<DimBranchPlan> DimBranchPlans
		{
			get
			{
				return this._dimBranchPlans;
			}
		}
		
		private IList<Route> _routes = new List<Route>();
		public virtual IList<Route> Routes
		{
			get
			{
				return this._routes;
			}
		}
		
	}
}
#pragma warning restore 1591
