#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.SDM;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class BusinessUnit
	{
		private string _sPBUName;
		public virtual string SPBUName
		{
			get
			{
				return this._sPBUName;
			}
			set
			{
				this._sPBUName = value;
			}
		}
		
		private string _sAPBUID;
		public virtual string SAPBUID
		{
			get
			{
				return this._sAPBUID;
			}
			set
			{
				this._sAPBUID = value;
			}
		}
		
		private string _bUName;
		public virtual string BUName
		{
			get
			{
				return this._bUName;
			}
			set
			{
				this._bUName = value;
			}
		}
		
		private int _bUID;
		public virtual int BUID
		{
			get
			{
				return this._bUID;
			}
			set
			{
				this._bUID = value;
			}
		}
		
		private IList<Region> _regions = new List<Region>();
		public virtual IList<Region> Regions
		{
			get
			{
				return this._regions;
			}
		}
		
	}
}
#pragma warning restore 1591
