#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class ChainHier
	{
		private int? _sAPRegionalChainID;
		public virtual int? SAPRegionalChainID
		{
			get
			{
				return this._sAPRegionalChainID;
			}
			set
			{
				this._sAPRegionalChainID = value;
			}
		}
		
		private int? _sAPNationalChainID;
		public virtual int? SAPNationalChainID
		{
			get
			{
				return this._sAPNationalChainID;
			}
			set
			{
				this._sAPNationalChainID = value;
			}
		}
		
		private int? _sAPLocalChainID;
		public virtual int? SAPLocalChainID
		{
			get
			{
				return this._sAPLocalChainID;
			}
			set
			{
				this._sAPLocalChainID = value;
			}
		}
		
		private string _regionalChainName;
		public virtual string RegionalChainName
		{
			get
			{
				return this._regionalChainName;
			}
			set
			{
				this._regionalChainName = value;
			}
		}
		
		private int _regionalChainID;
		public virtual int RegionalChainID
		{
			get
			{
				return this._regionalChainID;
			}
			set
			{
				this._regionalChainID = value;
			}
		}
		
		private string _nationalChainName;
		public virtual string NationalChainName
		{
			get
			{
				return this._nationalChainName;
			}
			set
			{
				this._nationalChainName = value;
			}
		}
		
		private int _nationalChainID;
		public virtual int NationalChainID
		{
			get
			{
				return this._nationalChainID;
			}
			set
			{
				this._nationalChainID = value;
			}
		}
		
		private string _localChainName;
		public virtual string LocalChainName
		{
			get
			{
				return this._localChainName;
			}
			set
			{
				this._localChainName = value;
			}
		}
		
		private int _localChainID;
		public virtual int LocalChainID
		{
			get
			{
				return this._localChainID;
			}
			set
			{
				this._localChainID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
