#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class ConsumptionLog_OFD
	{
		private int _logID;
		public virtual int LogID
		{
			get
			{
				return this._logID;
			}
			set
			{
				this._logID = value;
			}
		}
		
		private string _pageURL;
		public virtual string PageURL
		{
			get
			{
				return this._pageURL;
			}
			set
			{
				this._pageURL = value;
			}
		}
		
		private DateTime? _requestTime;
		public virtual DateTime? RequestTime
		{
			get
			{
				return this._requestTime;
			}
			set
			{
				this._requestTime = value;
			}
		}
		
		private double? _duration;
		public virtual double? Duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				this._duration = value;
			}
		}
		
		private string _gSN;
		public virtual string GSN
		{
			get
			{
				return this._gSN;
			}
			set
			{
				this._gSN = value;
			}
		}
		
		private double? _durationInMS;
		public virtual double? DurationInMS
		{
			get
			{
				return this._durationInMS;
			}
		}
		
	}
}
#pragma warning restore 1591
