#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class FactOFDDailyMetric
	{
		private DateTime? _recordDate;
		public virtual DateTime? RecordDate
		{
			get
			{
				return this._recordDate;
			}
			set
			{
				this._recordDate = value;
			}
		}
		
		private string _metricID;
		public virtual string MetricID
		{
			get
			{
				return this._metricID;
			}
			set
			{
				this._metricID = value;
			}
		}
		
		private DateTime? _metricDate;
		public virtual DateTime? MetricDate
		{
			get
			{
				return this._metricDate;
			}
			set
			{
				this._metricDate = value;
			}
		}
		
		private decimal? _metric;
		public virtual decimal? Metric
		{
			get
			{
				return this._metric;
			}
			set
			{
				this._metric = value;
			}
		}
		
		private int _branchID;
		public virtual int BranchID
		{
			get
			{
				return this._branchID;
			}
			set
			{
				this._branchID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
