#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class LocationChain
	{
		private int? _sAPRegionalChainID;
		public virtual int? SAPRegionalChainID
		{
			get
			{
				return this._sAPRegionalChainID;
			}
			set
			{
				this._sAPRegionalChainID = value;
			}
		}
		
		private int? _sAPNationalChainID;
		public virtual int? SAPNationalChainID
		{
			get
			{
				return this._sAPNationalChainID;
			}
			set
			{
				this._sAPNationalChainID = value;
			}
		}
		
		private int? _sAPLocalChainID;
		public virtual int? SAPLocalChainID
		{
			get
			{
				return this._sAPLocalChainID;
			}
			set
			{
				this._sAPLocalChainID = value;
			}
		}
		
		private int _regionID;
		public virtual int RegionID
		{
			get
			{
				return this._regionID;
			}
			set
			{
				this._regionID = value;
			}
		}
		
		private string _regionalChainName;
		public virtual string RegionalChainName
		{
			get
			{
				return this._regionalChainName;
			}
			set
			{
				this._regionalChainName = value;
			}
		}
		
		private int _regionalChainID;
		public virtual int RegionalChainID
		{
			get
			{
				return this._regionalChainID;
			}
			set
			{
				this._regionalChainID = value;
			}
		}
		
		private string _region;
		public virtual string Region
		{
			get
			{
				return this._region;
			}
			set
			{
				this._region = value;
			}
		}
		
		private string _nationalChainName;
		public virtual string NationalChainName
		{
			get
			{
				return this._nationalChainName;
			}
			set
			{
				this._nationalChainName = value;
			}
		}
		
		private int _nationalChainID;
		public virtual int NationalChainID
		{
			get
			{
				return this._nationalChainID;
			}
			set
			{
				this._nationalChainID = value;
			}
		}
		
		private string _localChainName;
		public virtual string LocalChainName
		{
			get
			{
				return this._localChainName;
			}
			set
			{
				this._localChainName = value;
			}
		}
		
		private int _localChainID;
		public virtual int LocalChainID
		{
			get
			{
				return this._localChainID;
			}
			set
			{
				this._localChainID = value;
			}
		}
		
		private int _bUID;
		public virtual int BUID
		{
			get
			{
				return this._bUID;
			}
			set
			{
				this._bUID = value;
			}
		}
		
		private string _bU;
		public virtual string BU
		{
			get
			{
				return this._bU;
			}
			set
			{
				this._bU = value;
			}
		}
		
		private string _branchName;
		public virtual string BranchName
		{
			get
			{
				return this._branchName;
			}
			set
			{
				this._branchName = value;
			}
		}
		
		private int _branchID;
		public virtual int BranchID
		{
			get
			{
				return this._branchID;
			}
			set
			{
				this._branchID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
