#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.SDM;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class MeasursType
	{
		private int _measursID;
		public virtual int MeasursID
		{
			get
			{
				return this._measursID;
			}
			set
			{
				this._measursID = value;
			}
		}
		
		private int? _deptID;
		public virtual int? DeptID
		{
			get
			{
				return this._deptID;
			}
			set
			{
				this._deptID = value;
			}
		}
		
		private string _measursType1;
		public virtual string MeasursType1
		{
			get
			{
				return this._measursType1;
			}
			set
			{
				this._measursType1 = value;
			}
		}
		
		private Department _department;
		public virtual Department Department
		{
			get
			{
				return this._department;
			}
			set
			{
				this._department = value;
			}
		}
		
	}
}
#pragma warning restore 1591
