#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.SDM;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBAccountMilestone
	{
		private int _accountMilestoneID;
		public virtual int AccountMilestoneID
		{
			get
			{
				return this._accountMilestoneID;
			}
			set
			{
				this._accountMilestoneID = value;
			}
		}
		
		private int? _nationalChainID;
		public virtual int? NationalChainID
		{
			get
			{
				return this._nationalChainID;
			}
			set
			{
				this._nationalChainID = value;
			}
		}
		
		private int _milestoneID;
		public virtual int MilestoneID
		{
			get
			{
				return this._milestoneID;
			}
			set
			{
				this._milestoneID = value;
			}
		}
		
		private int? _associatdMilestoneID;
		public virtual int? AssociatdMilestoneID
		{
			get
			{
				return this._associatdMilestoneID;
			}
			set
			{
				this._associatdMilestoneID = value;
			}
		}
		
		private int? _daysCalculation;
		public virtual int? DaysCalculation
		{
			get
			{
				return this._daysCalculation;
			}
			set
			{
				this._daysCalculation = value;
			}
		}
		
		private int? _numberOfDays;
		public virtual int? NumberOfDays
		{
			get
			{
				return this._numberOfDays;
			}
			set
			{
				this._numberOfDays = value;
			}
		}
		
		private string _precedenceRule;
		public virtual string PrecedenceRule
		{
			get
			{
				return this._precedenceRule;
			}
			set
			{
				this._precedenceRule = value;
			}
		}
		
		private string _approvalRule;
		public virtual string ApprovalRule
		{
			get
			{
				return this._approvalRule;
			}
			set
			{
				this._approvalRule = value;
			}
		}
		
		private bool _isActive;
		public virtual bool IsActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				this._isActive = value;
			}
		}
		
		private string _createdBy;
		public virtual string CreatedBy
		{
			get
			{
				return this._createdBy;
			}
			set
			{
				this._createdBy = value;
			}
		}
		
		private DateTime _createdDate;
		public virtual DateTime CreatedDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				this._createdDate = value;
			}
		}
		
		private string _modifiedBy;
		public virtual string ModifiedBy
		{
			get
			{
				return this._modifiedBy;
			}
			set
			{
				this._modifiedBy = value;
			}
		}
		
		private DateTime _modifiedDate;
		public virtual DateTime ModifiedDate
		{
			get
			{
				return this._modifiedDate;
			}
			set
			{
				this._modifiedDate = value;
			}
		}
		
		private bool _copyAttachment;
		public virtual bool CopyAttachment
		{
			get
			{
				return this._copyAttachment;
			}
			set
			{
				this._copyAttachment = value;
			}
		}
		
		private string _dayPeriod;
		public virtual string DayPeriod
		{
			get
			{
				return this._dayPeriod;
			}
			set
			{
				this._dayPeriod = value;
			}
		}
		
		private int? _milestoneOrder;
		public virtual int? MilestoneOrder
		{
			get
			{
				return this._milestoneOrder;
			}
			set
			{
				this._milestoneOrder = value;
			}
		}
		
		private int? _attachmentTypeID;
		public virtual int? AttachmentTypeID
		{
			get
			{
				return this._attachmentTypeID;
			}
			set
			{
				this._attachmentTypeID = value;
			}
		}
		
		private string _calculationType;
		public virtual string CalculationType
		{
			get
			{
				return this._calculationType;
			}
			set
			{
				this._calculationType = value;
			}
		}
		
		private int? _endPointMilestoneId;
		public virtual int? EndPointMilestoneId
		{
			get
			{
				return this._endPointMilestoneId;
			}
			set
			{
				this._endPointMilestoneId = value;
			}
		}
		
		private PBMilestone _pBMilestone;
		public virtual PBMilestone PBMilestone
		{
			get
			{
				return this._pBMilestone;
			}
			set
			{
				this._pBMilestone = value;
			}
		}
		
	}
}
#pragma warning restore 1591
