#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.SDM;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBAttachmentType
	{
		private int _attachmentTypeID;
		public virtual int AttachmentTypeID
		{
			get
			{
				return this._attachmentTypeID;
			}
			set
			{
				this._attachmentTypeID = value;
			}
		}
		
		private string _attachmentTypeName;
		public virtual string AttachmentTypeName
		{
			get
			{
				return this._attachmentTypeName;
			}
			set
			{
				this._attachmentTypeName = value;
			}
		}
		
		private IList<PBPromotionAttachment> _pBPromotionAttachments = new List<PBPromotionAttachment>();
		public virtual IList<PBPromotionAttachment> PBPromotionAttachments
		{
			get
			{
				return this._pBPromotionAttachments;
			}
		}
		
	}
}
#pragma warning restore 1591
