#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBChannelHier
	{
		private string _superChannelName;
		public virtual string SuperChannelName
		{
			get
			{
				return this._superChannelName;
			}
			set
			{
				this._superChannelName = value;
			}
		}
		
		private int _superChannelID;
		public virtual int SuperChannelID
		{
			get
			{
				return this._superChannelID;
			}
			set
			{
				this._superChannelID = value;
			}
		}
		
		private string _sAPSuperChannelID;
		public virtual string SAPSuperChannelID
		{
			get
			{
				return this._sAPSuperChannelID;
			}
			set
			{
				this._sAPSuperChannelID = value;
			}
		}
		
		private string _sAPChannelID;
		public virtual string SAPChannelID
		{
			get
			{
				return this._sAPChannelID;
			}
			set
			{
				this._sAPChannelID = value;
			}
		}
		
		private string _channelName;
		public virtual string ChannelName
		{
			get
			{
				return this._channelName;
			}
			set
			{
				this._channelName = value;
			}
		}
		
		private int _channelID;
		public virtual int ChannelID
		{
			get
			{
				return this._channelID;
			}
			set
			{
				this._channelID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
