#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBCustomCategoryPackage
	{
		private string _packageName;
		public virtual string PackageName
		{
			get
			{
				return this._packageName;
			}
			set
			{
				this._packageName = value;
			}
		}
		
		private int _packageID;
		public virtual int PackageID
		{
			get
			{
				return this._packageID;
			}
			set
			{
				this._packageID = value;
			}
		}
		
		private string _categoryGroupName;
		public virtual string CategoryGroupName
		{
			get
			{
				return this._categoryGroupName;
			}
			set
			{
				this._categoryGroupName = value;
			}
		}
		
	}
}
#pragma warning restore 1591
