#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBLocationHier
	{
		private string _sPRegionName;
		public virtual string SPRegionName
		{
			get
			{
				return this._sPRegionName;
			}
			set
			{
				this._sPRegionName = value;
			}
		}
		
		private string _sPBUName;
		public virtual string SPBUName
		{
			get
			{
				return this._sPBUName;
			}
			set
			{
				this._sPBUName = value;
			}
		}
		
		private string _sPBranchName;
		public virtual string SPBranchName
		{
			get
			{
				return this._sPBranchName;
			}
			set
			{
				this._sPBranchName = value;
			}
		}
		
		private string _sAPRegionID;
		public virtual string SAPRegionID
		{
			get
			{
				return this._sAPRegionID;
			}
			set
			{
				this._sAPRegionID = value;
			}
		}
		
		private string _sAPBUID;
		public virtual string SAPBUID
		{
			get
			{
				return this._sAPBUID;
			}
			set
			{
				this._sAPBUID = value;
			}
		}
		
		private string _sAPBranchID;
		public virtual string SAPBranchID
		{
			get
			{
				return this._sAPBranchID;
			}
			set
			{
				this._sAPBranchID = value;
			}
		}
		
		private string _sAPAreaID;
		public virtual string SAPAreaID
		{
			get
			{
				return this._sAPAreaID;
			}
			set
			{
				this._sAPAreaID = value;
			}
		}
		
		private string _regionName;
		public virtual string RegionName
		{
			get
			{
				return this._regionName;
			}
			set
			{
				this._regionName = value;
			}
		}
		
		private int _regionID;
		public virtual int RegionID
		{
			get
			{
				return this._regionID;
			}
			set
			{
				this._regionID = value;
			}
		}
		
		private string _bUName;
		public virtual string BUName
		{
			get
			{
				return this._bUName;
			}
			set
			{
				this._bUName = value;
			}
		}
		
		private int _bUID;
		public virtual int BUID
		{
			get
			{
				return this._bUID;
			}
			set
			{
				this._bUID = value;
			}
		}
		
		private string _branchName;
		public virtual string BranchName
		{
			get
			{
				return this._branchName;
			}
			set
			{
				this._branchName = value;
			}
		}
		
		private int _branchID;
		public virtual int BranchID
		{
			get
			{
				return this._branchID;
			}
			set
			{
				this._branchID = value;
			}
		}
		
		private string _areaName;
		public virtual string AreaName
		{
			get
			{
				return this._areaName;
			}
			set
			{
				this._areaName = value;
			}
		}
		
		private int _areaID;
		public virtual int AreaID
		{
			get
			{
				return this._areaID;
			}
			set
			{
				this._areaID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
