#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.SDM;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBMaterial
	{
		private int _materialID;
		public virtual int MaterialID
		{
			get
			{
				return this._materialID;
			}
			set
			{
				this._materialID = value;
			}
		}
		
		private string _sAPMaterialID;
		public virtual string SAPMaterialID
		{
			get
			{
				return this._sAPMaterialID;
			}
			set
			{
				this._sAPMaterialID = value;
			}
		}
		
		private string _materialName;
		public virtual string MaterialName
		{
			get
			{
				return this._materialName;
			}
			set
			{
				this._materialName = value;
			}
		}
		
		private int? _franchisorID;
		public virtual int? FranchisorID
		{
			get
			{
				return this._franchisorID;
			}
			set
			{
				this._franchisorID = value;
			}
		}
		
		private int? _bevTypeID;
		public virtual int? BevTypeID
		{
			get
			{
				return this._bevTypeID;
			}
			set
			{
				this._bevTypeID = value;
			}
		}
		
		private int? _brandID;
		public virtual int? BrandID
		{
			get
			{
				return this._brandID;
			}
			set
			{
				this._brandID = value;
			}
		}
		
		private int? _flavorID;
		public virtual int? FlavorID
		{
			get
			{
				return this._flavorID;
			}
			set
			{
				this._flavorID = value;
			}
		}
		
		private int? _packageID;
		public virtual int? PackageID
		{
			get
			{
				return this._packageID;
			}
			set
			{
				this._packageID = value;
			}
		}
		
		private int? _calorieClassID;
		public virtual int? CalorieClassID
		{
			get
			{
				return this._calorieClassID;
			}
			set
			{
				this._calorieClassID = value;
			}
		}
		
		private int? _internalCategoryID;
		public virtual int? InternalCategoryID
		{
			get
			{
				return this._internalCategoryID;
			}
			set
			{
				this._internalCategoryID = value;
			}
		}
		
		private int? _caffeineClaimID;
		public virtual int? CaffeineClaimID
		{
			get
			{
				return this._caffeineClaimID;
			}
			set
			{
				this._caffeineClaimID = value;
			}
		}
		
		private int? _changeTrackNumber;
		public virtual int? ChangeTrackNumber
		{
			get
			{
				return this._changeTrackNumber;
			}
			set
			{
				this._changeTrackNumber = value;
			}
		}
		
		private DateTime? _lastModified;
		public virtual DateTime? LastModified
		{
			get
			{
				return this._lastModified;
			}
			set
			{
				this._lastModified = value;
			}
		}
		
		private int? _pPGID;
		public virtual int? PPGID
		{
			get
			{
				return this._pPGID;
			}
			set
			{
				this._pPGID = value;
			}
		}
		
		private int? _baseUoMID;
		public virtual int? BaseUoMID
		{
			get
			{
				return this._baseUoMID;
			}
			set
			{
				this._baseUoMID = value;
			}
		}
		
		private int? _supplyChainProductSK;
		public virtual int? SupplyChainProductSK
		{
			get
			{
				return this._supplyChainProductSK;
			}
			set
			{
				this._supplyChainProductSK = value;
			}
		}
		
		private string _sAPMaterialNumber;
		public virtual string SAPMaterialNumber
		{
			get
			{
				return this._sAPMaterialNumber;
			}
			set
			{
				this._sAPMaterialNumber = value;
			}
		}
		
		private bool _activeInRM;
		public virtual bool ActiveInRM
		{
			get
			{
				return this._activeInRM;
			}
			set
			{
				this._activeInRM = value;
			}
		}
		
		private DateTime _rMStatusSetDate;
		public virtual DateTime RMStatusSetDate
		{
			get
			{
				return this._rMStatusSetDate;
			}
			set
			{
				this._rMStatusSetDate = value;
			}
		}
		
		private PBPackage _pBPackage;
		public virtual PBPackage PBPackage
		{
			get
			{
				return this._pBPackage;
			}
			set
			{
				this._pBPackage = value;
			}
		}
		
		private PBBrand _pBBrand;
		public virtual PBBrand PBBrand
		{
			get
			{
				return this._pBBrand;
			}
			set
			{
				this._pBBrand = value;
			}
		}
		
	}
}
#pragma warning restore 1591
