#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.SDM;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBNationalChain
	{
		private int _nationalChainID;
		public virtual int NationalChainID
		{
			get
			{
				return this._nationalChainID;
			}
			set
			{
				this._nationalChainID = value;
			}
		}
		
		private int? _sAPNationalChainID;
		public virtual int? SAPNationalChainID
		{
			get
			{
				return this._sAPNationalChainID;
			}
			set
			{
				this._sAPNationalChainID = value;
			}
		}
		
		private string _nationalChainName;
		public virtual string NationalChainName
		{
			get
			{
				return this._nationalChainName;
			}
			set
			{
				this._nationalChainName = value;
			}
		}
		
		private int? _changeTrackNumber;
		public virtual int? ChangeTrackNumber
		{
			get
			{
				return this._changeTrackNumber;
			}
			set
			{
				this._changeTrackNumber = value;
			}
		}
		
		private DateTime? _lastModified;
		public virtual DateTime? LastModified
		{
			get
			{
				return this._lastModified;
			}
			set
			{
				this._lastModified = value;
			}
		}
		
		private IList<PBRegionalChain> _pBRegionalChains = new List<PBRegionalChain>();
		public virtual IList<PBRegionalChain> PBRegionalChains
		{
			get
			{
				return this._pBRegionalChains;
			}
		}
		
	}
}
#pragma warning restore 1591
