#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.SDM;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBPackageType
	{
		private string _sAPPackageTypeID;
		public virtual string SAPPackageTypeID
		{
			get
			{
				return this._sAPPackageTypeID;
			}
			set
			{
				this._sAPPackageTypeID = value;
			}
		}
		
		private string _packageTypeName;
		public virtual string PackageTypeName
		{
			get
			{
				return this._packageTypeName;
			}
			set
			{
				this._packageTypeName = value;
			}
		}
		
		private int _packageTypeID;
		public virtual int PackageTypeID
		{
			get
			{
				return this._packageTypeID;
			}
			set
			{
				this._packageTypeID = value;
			}
		}
		
		private string _sPPackageTypeName;
		public virtual string SPPackageTypeName
		{
			get
			{
				return this._sPPackageTypeName;
			}
			set
			{
				this._sPPackageTypeName = value;
			}
		}
		
		private DateTime? _lastModified;
		public virtual DateTime? LastModified
		{
			get
			{
				return this._lastModified;
			}
			set
			{
				this._lastModified = value;
			}
		}
		
		private int? _changeTrackNumber;
		public virtual int? ChangeTrackNumber
		{
			get
			{
				return this._changeTrackNumber;
			}
			set
			{
				this._changeTrackNumber = value;
			}
		}
		
		private IList<PBPackage> _pBPackages = new List<PBPackage>();
		public virtual IList<PBPackage> PBPackages
		{
			get
			{
				return this._pBPackages;
			}
		}
		
	}
}
#pragma warning restore 1591
