#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.SDM;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBPackage
	{
		private string _sPPackageName;
		public virtual string SPPackageName
		{
			get
			{
				return this._sPPackageName;
			}
			set
			{
				this._sPPackageName = value;
			}
		}
		
		private string _source;
		public virtual string Source
		{
			get
			{
				return this._source;
			}
			set
			{
				this._source = value;
			}
		}
		
		private string _rMPackageID;
		public virtual string RMPackageID
		{
			get
			{
				return this._rMPackageID;
			}
			set
			{
				this._rMPackageID = value;
			}
		}
		
		private int? _packageTypeID;
		public virtual int? PackageTypeID
		{
			get
			{
				return this._packageTypeID;
			}
			set
			{
				this._packageTypeID = value;
			}
		}
		
		private string _packageName;
		public virtual string PackageName
		{
			get
			{
				return this._packageName;
			}
			set
			{
				this._packageName = value;
			}
		}
		
		private int _packageID;
		public virtual int PackageID
		{
			get
			{
				return this._packageID;
			}
			set
			{
				this._packageID = value;
			}
		}
		
		private int? _packageConfID;
		public virtual int? PackageConfID
		{
			get
			{
				return this._packageConfID;
			}
			set
			{
				this._packageConfID = value;
			}
		}
		
		private string _friendlyName;
		public virtual string FriendlyName
		{
			get
			{
				return this._friendlyName;
			}
			set
			{
				this._friendlyName = value;
			}
		}
		
		private bool _active;
		public virtual bool Active
		{
			get
			{
				return this._active;
			}
			set
			{
				this._active = value;
			}
		}
		
		private DateTime? _lastModified;
		public virtual DateTime? LastModified
		{
			get
			{
				return this._lastModified;
			}
			set
			{
				this._lastModified = value;
			}
		}
		
		private int? _changeTrackNumber;
		public virtual int? ChangeTrackNumber
		{
			get
			{
				return this._changeTrackNumber;
			}
			set
			{
				this._changeTrackNumber = value;
			}
		}
		
		private PBPackageType _pBPackageType;
		public virtual PBPackageType PBPackageType
		{
			get
			{
				return this._pBPackageType;
			}
			set
			{
				this._pBPackageType = value;
			}
		}
		
		private IList<PBMaterial> _pBMaterials = new List<PBMaterial>();
		public virtual IList<PBMaterial> PBMaterials
		{
			get
			{
				return this._pBMaterials;
			}
		}
		
	}
}
#pragma warning restore 1591
