#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBPromotionBrand
	{
		private int _promotionID;
		public virtual int PromotionID
		{
			get
			{
				return this._promotionID;
			}
			set
			{
				this._promotionID = value;
			}
		}
		
		private int? _brandID;
		public virtual int? BrandID
		{
			get
			{
				return this._brandID;
			}
			set
			{
				this._brandID = value;
			}
		}
		
		private int? _trademarkID;
		public virtual int? TrademarkID
		{
			get
			{
				return this._trademarkID;
			}
			set
			{
				this._trademarkID = value;
			}
		}
		
		private int _promotionBrandID;
		public virtual int PromotionBrandID
		{
			get
			{
				return this._promotionBrandID;
			}
			set
			{
				this._promotionBrandID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
