#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBPromotionSystem
	{
		private int _promotionSystemID;
		public virtual int PromotionSystemID
		{
			get
			{
				return this._promotionSystemID;
			}
			set
			{
				this._promotionSystemID = value;
			}
		}
		
		private int _promotionID;
		public virtual int PromotionID
		{
			get
			{
				return this._promotionID;
			}
			set
			{
				this._promotionID = value;
			}
		}
		
		private int _systemID;
		public virtual int SystemID
		{
			get
			{
				return this._systemID;
			}
			set
			{
				this._systemID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
