#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBPromotionPackage
	{
		private int? _promotionID;
		public virtual int? PromotionID
		{
			get
			{
				return this._promotionID;
			}
			set
			{
				this._promotionID = value;
			}
		}
		
		private int _promotionPackageID;
		public virtual int PromotionPackageID
		{
			get
			{
				return this._promotionPackageID;
			}
			set
			{
				this._promotionPackageID = value;
			}
		}
		
		private int? _packageTypeID;
		public virtual int? PackageTypeID
		{
			get
			{
				return this._packageTypeID;
			}
			set
			{
				this._packageTypeID = value;
			}
		}
		
		private int? _packageConfID;
		public virtual int? PackageConfID
		{
			get
			{
				return this._packageConfID;
			}
			set
			{
				this._packageConfID = value;
			}
		}
		
		private int? _packageID;
		public virtual int? PackageID
		{
			get
			{
				return this._packageID;
			}
			set
			{
				this._packageID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
