#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBPromotionAttachmentSystem
	{
		private int _promotionAttachmentSystemID;
		public virtual int PromotionAttachmentSystemID
		{
			get
			{
				return this._promotionAttachmentSystemID;
			}
			set
			{
				this._promotionAttachmentSystemID = value;
			}
		}
		
		private int? _promotionAttachmentID;
		public virtual int? PromotionAttachmentID
		{
			get
			{
				return this._promotionAttachmentID;
			}
			set
			{
				this._promotionAttachmentID = value;
			}
		}
		
		private int? _systemId;
		public virtual int? SystemId
		{
			get
			{
				return this._systemId;
			}
			set
			{
				this._systemId = value;
			}
		}
		
	}
}
#pragma warning restore 1591
