#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBPromotionChannel
	{
		private int _promotionChannelID;
		public virtual int PromotionChannelID
		{
			get
			{
				return this._promotionChannelID;
			}
			set
			{
				this._promotionChannelID = value;
			}
		}
		
		private int? _superChannelID;
		public virtual int? SuperChannelID
		{
			get
			{
				return this._superChannelID;
			}
			set
			{
				this._superChannelID = value;
			}
		}
		
		private int? _channelID;
		public virtual int? ChannelID
		{
			get
			{
				return this._channelID;
			}
			set
			{
				this._channelID = value;
			}
		}
		
		private int? _promotionID;
		public virtual int? PromotionID
		{
			get
			{
				return this._promotionID;
			}
			set
			{
				this._promotionID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
