#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.SDM;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBPromotionAttachment
	{
		private int _promotionAttachmentID;
		public virtual int PromotionAttachmentID
		{
			get
			{
				return this._promotionAttachmentID;
			}
			set
			{
				this._promotionAttachmentID = value;
			}
		}
		
		private string _attachmentURL;
		public virtual string AttachmentURL
		{
			get
			{
				return this._attachmentURL;
			}
			set
			{
				this._attachmentURL = value;
			}
		}
		
		private int? _attachmentTypeID;
		public virtual int? AttachmentTypeID
		{
			get
			{
				return this._attachmentTypeID;
			}
			set
			{
				this._attachmentTypeID = value;
			}
		}
		
		private string _attachmentName;
		public virtual string AttachmentName
		{
			get
			{
				return this._attachmentName;
			}
			set
			{
				this._attachmentName = value;
			}
		}
		
		private int _promotionID;
		public virtual int PromotionID
		{
			get
			{
				return this._promotionID;
			}
			set
			{
				this._promotionID = value;
			}
		}
		
		private int? _attachmentSize;
		public virtual int? AttachmentSize
		{
			get
			{
				return this._attachmentSize;
			}
			set
			{
				this._attachmentSize = value;
			}
		}
		
		private string _attachmentDocumentID;
		public virtual string AttachmentDocumentID
		{
			get
			{
				return this._attachmentDocumentID;
			}
			set
			{
				this._attachmentDocumentID = value;
			}
		}
		
		private DateTime? _attachmentDateModified;
		public virtual DateTime? AttachmentDateModified
		{
			get
			{
				return this._attachmentDateModified;
			}
			set
			{
				this._attachmentDateModified = value;
			}
		}
		
		private int? _systemId;
		public virtual int? SystemId
		{
			get
			{
				return this._systemId;
			}
			set
			{
				this._systemId = value;
			}
		}
		
		private string _displaySystemIds;
		public virtual string DisplaySystemIds
		{
			get
			{
				return this._displaySystemIds;
			}
			set
			{
				this._displaySystemIds = value;
			}
		}
		
		private PBAttachmentType _pBAttachmentType;
		public virtual PBAttachmentType PBAttachmentType
		{
			get
			{
				return this._pBAttachmentType;
			}
			set
			{
				this._pBAttachmentType = value;
			}
		}
		
	}
}
#pragma warning restore 1591
