#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.SDM;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBProgramMilestoneAttachment
	{
		private int _milestoneAttachmentID;
		public virtual int MilestoneAttachmentID
		{
			get
			{
				return this._milestoneAttachmentID;
			}
			set
			{
				this._milestoneAttachmentID = value;
			}
		}
		
		private int _milestoneID;
		public virtual int MilestoneID
		{
			get
			{
				return this._milestoneID;
			}
			set
			{
				this._milestoneID = value;
			}
		}
		
		private int? _systemID;
		public virtual int? SystemID
		{
			get
			{
				return this._systemID;
			}
			set
			{
				this._systemID = value;
			}
		}
		
		private int _programID;
		public virtual int ProgramID
		{
			get
			{
				return this._programID;
			}
			set
			{
				this._programID = value;
			}
		}
		
		private int? _attachmentTypeID;
		public virtual int? AttachmentTypeID
		{
			get
			{
				return this._attachmentTypeID;
			}
			set
			{
				this._attachmentTypeID = value;
			}
		}
		
		private int _approvalStatusID;
		public virtual int ApprovalStatusID
		{
			get
			{
				return this._approvalStatusID;
			}
			set
			{
				this._approvalStatusID = value;
			}
		}
		
		private string _documentName;
		public virtual string DocumentName
		{
			get
			{
				return this._documentName;
			}
			set
			{
				this._documentName = value;
			}
		}
		
		private string _documentURL;
		public virtual string DocumentURL
		{
			get
			{
				return this._documentURL;
			}
			set
			{
				this._documentURL = value;
			}
		}
		
		private string _documentID;
		public virtual string DocumentID
		{
			get
			{
				return this._documentID;
			}
			set
			{
				this._documentID = value;
			}
		}
		
		private string _documentSize;
		public virtual string DocumentSize
		{
			get
			{
				return this._documentSize;
			}
			set
			{
				this._documentSize = value;
			}
		}
		
		private DateTime? _documentModifiedDate;
		public virtual DateTime? DocumentModifiedDate
		{
			get
			{
				return this._documentModifiedDate;
			}
			set
			{
				this._documentModifiedDate = value;
			}
		}
		
		private string _displaySystemNames;
		public virtual string DisplaySystemNames
		{
			get
			{
				return this._displaySystemNames;
			}
			set
			{
				this._displaySystemNames = value;
			}
		}
		
		private PBProgram _pBProgram;
		public virtual PBProgram PBProgram
		{
			get
			{
				return this._pBProgram;
			}
			set
			{
				this._pBProgram = value;
			}
		}
		
		private PBMilestone _pBMilestone;
		public virtual PBMilestone PBMilestone
		{
			get
			{
				return this._pBMilestone;
			}
			set
			{
				this._pBMilestone = value;
			}
		}
		
		private PBStatusNationalAccount _pBStatusNationalAccount;
		public virtual PBStatusNationalAccount PBStatusNationalAccount
		{
			get
			{
				return this._pBStatusNationalAccount;
			}
			set
			{
				this._pBStatusNationalAccount = value;
			}
		}
		
	}
}
#pragma warning restore 1591
