#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.SDM;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBProgramAccount
	{
		private int _programAccountID;
		public virtual int ProgramAccountID
		{
			get
			{
				return this._programAccountID;
			}
			set
			{
				this._programAccountID = value;
			}
		}
		
		private int _programID;
		public virtual int ProgramID
		{
			get
			{
				return this._programID;
			}
			set
			{
				this._programID = value;
			}
		}
		
		private int? _nationalAccountID;
		public virtual int? NationalAccountID
		{
			get
			{
				return this._nationalAccountID;
			}
			set
			{
				this._nationalAccountID = value;
			}
		}
		
		private int? _regionalAccountID;
		public virtual int? RegionalAccountID
		{
			get
			{
				return this._regionalAccountID;
			}
			set
			{
				this._regionalAccountID = value;
			}
		}
		
		private int? _localAccountID;
		public virtual int? LocalAccountID
		{
			get
			{
				return this._localAccountID;
			}
			set
			{
				this._localAccountID = value;
			}
		}
		
		private PBProgram _pBProgram;
		public virtual PBProgram PBProgram
		{
			get
			{
				return this._pBProgram;
			}
			set
			{
				this._pBProgram = value;
			}
		}
		
	}
}
#pragma warning restore 1591
