#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBPromotionGeoRelevancy
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private int? _promotionId;
		public virtual int? PromotionId
		{
			get
			{
				return this._promotionId;
			}
			set
			{
				this._promotionId = value;
			}
		}
		
		private int? _bUID;
		public virtual int? BUID
		{
			get
			{
				return this._bUID;
			}
			set
			{
				this._bUID = value;
			}
		}
		
		private int? _regionId;
		public virtual int? RegionId
		{
			get
			{
				return this._regionId;
			}
			set
			{
				this._regionId = value;
			}
		}
		
		private int? _areaId;
		public virtual int? AreaId
		{
			get
			{
				return this._areaId;
			}
			set
			{
				this._areaId = value;
			}
		}
		
		private int? _branchId;
		public virtual int? BranchId
		{
			get
			{
				return this._branchId;
			}
			set
			{
				this._branchId = value;
			}
		}
		
		private int? _systemID;
		public virtual int? SystemID
		{
			get
			{
				return this._systemID;
			}
			set
			{
				this._systemID = value;
			}
		}
		
		private int? _zoneID;
		public virtual int? ZoneID
		{
			get
			{
				return this._zoneID;
			}
			set
			{
				this._zoneID = value;
			}
		}
		
		private int? _divisionID;
		public virtual int? DivisionID
		{
			get
			{
				return this._divisionID;
			}
			set
			{
				this._divisionID = value;
			}
		}
		
		private int? _bCRegionID;
		public virtual int? BCRegionID
		{
			get
			{
				return this._bCRegionID;
			}
			set
			{
				this._bCRegionID = value;
			}
		}
		
		private int? _bottlerID;
		public virtual int? BottlerID
		{
			get
			{
				return this._bottlerID;
			}
			set
			{
				this._bottlerID = value;
			}
		}
		
		private int? _stateId;
		public virtual int? StateId
		{
			get
			{
				return this._stateId;
			}
			set
			{
				this._stateId = value;
			}
		}
		
	}
}
#pragma warning restore 1591
