#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.SDM;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBProgramPackage
	{
		private int _programPackageID;
		public virtual int ProgramPackageID
		{
			get
			{
				return this._programPackageID;
			}
			set
			{
				this._programPackageID = value;
			}
		}
		
		private int _programID;
		public virtual int ProgramID
		{
			get
			{
				return this._programID;
			}
			set
			{
				this._programID = value;
			}
		}
		
		private int _packageID;
		public virtual int PackageID
		{
			get
			{
				return this._packageID;
			}
			set
			{
				this._packageID = value;
			}
		}
		
		private PBProgram _pBProgram;
		public virtual PBProgram PBProgram
		{
			get
			{
				return this._pBProgram;
			}
			set
			{
				this._pBProgram = value;
			}
		}
		
	}
}
#pragma warning restore 1591
