#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBProgramSystem
	{
		private int _programSystemID;
		public virtual int ProgramSystemID
		{
			get
			{
				return this._programSystemID;
			}
			set
			{
				this._programSystemID = value;
			}
		}
		
		private int _programID;
		public virtual int ProgramID
		{
			get
			{
				return this._programID;
			}
			set
			{
				this._programID = value;
			}
		}
		
		private int _systemID;
		public virtual int SystemID
		{
			get
			{
				return this._systemID;
			}
			set
			{
				this._systemID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
