#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.SDM;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBPromotionDisplayLocation
	{
		private int _promoitionDisplayLocationID;
		public virtual int PromoitionDisplayLocationID
		{
			get
			{
				return this._promoitionDisplayLocationID;
			}
			set
			{
				this._promoitionDisplayLocationID = value;
			}
		}
		
		private int _promotionID;
		public virtual int PromotionID
		{
			get
			{
				return this._promotionID;
			}
			set
			{
				this._promotionID = value;
			}
		}
		
		private int? _displayLocationID;
		public virtual int? DisplayLocationID
		{
			get
			{
				return this._displayLocationID;
			}
			set
			{
				this._displayLocationID = value;
			}
		}
		
		private string _promotionDisplayLocationOther;
		public virtual string PromotionDisplayLocationOther
		{
			get
			{
				return this._promotionDisplayLocationOther;
			}
			set
			{
				this._promotionDisplayLocationOther = value;
			}
		}
		
		private string _displayRequirement;
		public virtual string DisplayRequirement
		{
			get
			{
				return this._displayRequirement;
			}
			set
			{
				this._displayRequirement = value;
			}
		}
		
		private PBRetailPromotion _pBRetailPromotion;
		public virtual PBRetailPromotion PBRetailPromotion
		{
			get
			{
				return this._pBRetailPromotion;
			}
			set
			{
				this._pBRetailPromotion = value;
			}
		}
		
	}
}
#pragma warning restore 1591
