#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBRoleSystem
	{
		private int _roleSystemID;
		public virtual int RoleSystemID
		{
			get
			{
				return this._roleSystemID;
			}
			set
			{
				this._roleSystemID = value;
			}
		}
		
		private int _roleID;
		public virtual int RoleID
		{
			get
			{
				return this._roleID;
			}
			set
			{
				this._roleID = value;
			}
		}
		
		private int _systemID;
		public virtual int SystemID
		{
			get
			{
				return this._systemID;
			}
			set
			{
				this._systemID = value;
			}
		}
		
		private bool? _defaultValue;
		public virtual bool? DefaultValue
		{
			get
			{
				return this._defaultValue;
			}
			set
			{
				this._defaultValue = value;
			}
		}
		
		private bool? _disabled;
		public virtual bool? Disabled
		{
			get
			{
				return this._disabled;
			}
			set
			{
				this._disabled = value;
			}
		}
		
	}
}
#pragma warning restore 1591
