#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBRPLItem
	{
		private int _itemID;
		public virtual int ItemID
		{
			get
			{
				return this._itemID;
			}
			set
			{
				this._itemID = value;
			}
		}
		
		private string _contentID;
		public virtual string ContentID
		{
			get
			{
				return this._contentID;
			}
			set
			{
				this._contentID = value;
			}
		}
		
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private DateTime? _startDate;
		public virtual DateTime? StartDate
		{
			get
			{
				return this._startDate;
			}
			set
			{
				this._startDate = value;
			}
		}
		
		private DateTime? _endDate;
		public virtual DateTime? EndDate
		{
			get
			{
				return this._endDate;
			}
			set
			{
				this._endDate = value;
			}
		}
		
		private DateTime? _expirationDateUTC;
		public virtual DateTime? ExpirationDateUTC
		{
			get
			{
				return this._expirationDateUTC;
			}
			set
			{
				this._expirationDateUTC = value;
			}
		}
		
		private string _referenceName;
		public virtual string ReferenceName
		{
			get
			{
				return this._referenceName;
			}
			set
			{
				this._referenceName = value;
			}
		}
		
		private int? _programNumber;
		public virtual int? ProgramNumber
		{
			get
			{
				return this._programNumber;
			}
			set
			{
				this._programNumber = value;
			}
		}
		
		private string _programDetail;
		public virtual string ProgramDetail
		{
			get
			{
				return this._programDetail;
			}
			set
			{
				this._programDetail = value;
			}
		}
		
		private string _price;
		public virtual string Price
		{
			get
			{
				return this._price;
			}
			set
			{
				this._price = value;
			}
		}
		
		private DateTime? _dateMail;
		public virtual DateTime? DateMail
		{
			get
			{
				return this._dateMail;
			}
			set
			{
				this._dateMail = value;
			}
		}
		
		private string _routeToMarkets;
		public virtual string RouteToMarkets
		{
			get
			{
				return this._routeToMarkets;
			}
			set
			{
				this._routeToMarkets = value;
			}
		}
		
		private string _bigBetsName;
		public virtual string BigBetsName
		{
			get
			{
				return this._bigBetsName;
			}
			set
			{
				this._bigBetsName = value;
			}
		}
		
		private bool? _costPerStore;
		public virtual bool? CostPerStore
		{
			get
			{
				return this._costPerStore;
			}
			set
			{
				this._costPerStore = value;
			}
		}
		
		private DateTime? _modifiedDateUTC;
		public virtual DateTime? ModifiedDateUTC
		{
			get
			{
				return this._modifiedDateUTC;
			}
			set
			{
				this._modifiedDateUTC = value;
			}
		}
		
		private DateTime _receivedDate;
		public virtual DateTime ReceivedDate
		{
			get
			{
				return this._receivedDate;
			}
			set
			{
				this._receivedDate = value;
			}
		}
		
		private bool? _testData;
		public virtual bool? TestData
		{
			get
			{
				return this._testData;
			}
			set
			{
				this._testData = value;
			}
		}
		
		private DateTime? _deletedDate;
		public virtual DateTime? DeletedDate
		{
			get
			{
				return this._deletedDate;
			}
			set
			{
				this._deletedDate = value;
			}
		}
		
		private string _informationCategory;
		public virtual string InformationCategory
		{
			get
			{
				return this._informationCategory;
			}
			set
			{
				this._informationCategory = value;
			}
		}
		
	}
}
#pragma warning restore 1591
