#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBStgMassUploadAttachment
	{
		private int _attachmentID;
		public virtual int AttachmentID
		{
			get
			{
				return this._attachmentID;
			}
			set
			{
				this._attachmentID = value;
			}
		}
		
		private int _stgPromotionID;
		public virtual int StgPromotionID
		{
			get
			{
				return this._stgPromotionID;
			}
			set
			{
				this._stgPromotionID = value;
			}
		}
		
		private string _attachmentName;
		public virtual string AttachmentName
		{
			get
			{
				return this._attachmentName;
			}
			set
			{
				this._attachmentName = value;
			}
		}
		
		private string _attachmentURL;
		public virtual string AttachmentURL
		{
			get
			{
				return this._attachmentURL;
			}
			set
			{
				this._attachmentURL = value;
			}
		}
		
		private int? _attachmentTypeID;
		public virtual int? AttachmentTypeID
		{
			get
			{
				return this._attachmentTypeID;
			}
			set
			{
				this._attachmentTypeID = value;
			}
		}
		
		private int? _attachmentSize;
		public virtual int? AttachmentSize
		{
			get
			{
				return this._attachmentSize;
			}
			set
			{
				this._attachmentSize = value;
			}
		}
		
		private string _attachmentDocumentID;
		public virtual string AttachmentDocumentID
		{
			get
			{
				return this._attachmentDocumentID;
			}
			set
			{
				this._attachmentDocumentID = value;
			}
		}
		
		private DateTime? _attachmentDateModified;
		public virtual DateTime? AttachmentDateModified
		{
			get
			{
				return this._attachmentDateModified;
			}
			set
			{
				this._attachmentDateModified = value;
			}
		}
		
		private string _displaySystem;
		public virtual string DisplaySystem
		{
			get
			{
				return this._displaySystem;
			}
			set
			{
				this._displaySystem = value;
			}
		}
		
	}
}
#pragma warning restore 1591
