#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBSystem
	{
		private int _systemID;
		public virtual int SystemID
		{
			get
			{
				return this._systemID;
			}
			set
			{
				this._systemID = value;
			}
		}
		
		private string _systemName;
		public virtual string SystemName
		{
			get
			{
				return this._systemName;
			}
			set
			{
				this._systemName = value;
			}
		}
		
		private string _termsetName;
		public virtual string TermsetName
		{
			get
			{
				return this._termsetName;
			}
			set
			{
				this._termsetName = value;
			}
		}
		
		private int? _sequence;
		public virtual int? Sequence
		{
			get
			{
				return this._sequence;
			}
			set
			{
				this._sequence = value;
			}
		}
		
		private string _promotionGeoRelevancy;
		public virtual string PromotionGeoRelevancy
		{
			get
			{
				return this._promotionGeoRelevancy;
			}
			set
			{
				this._promotionGeoRelevancy = value;
			}
		}
		
		private int? _promotionCopyRule;
		public virtual int? PromotionCopyRule
		{
			get
			{
				return this._promotionCopyRule;
			}
			set
			{
				this._promotionCopyRule = value;
			}
		}
		
		private int? _defaultPromotionStatus;
		public virtual int? DefaultPromotionStatus
		{
			get
			{
				return this._defaultPromotionStatus;
			}
			set
			{
				this._defaultPromotionStatus = value;
			}
		}
		
		private int? _bCSystemId;
		public virtual int? BCSystemId
		{
			get
			{
				return this._bCSystemId;
			}
			set
			{
				this._bCSystemId = value;
			}
		}
		
	}
}
#pragma warning restore 1591
