#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.SDM;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBTradeMark
	{
		private string _tradeMarkName;
		public virtual string TradeMarkName
		{
			get
			{
				return this._tradeMarkName;
			}
			set
			{
				this._tradeMarkName = value;
			}
		}
		
		private int _tradeMarkID;
		public virtual int TradeMarkID
		{
			get
			{
				return this._tradeMarkID;
			}
			set
			{
				this._tradeMarkID = value;
			}
		}
		
		private string _sAPTradeMarkID;
		public virtual string SAPTradeMarkID
		{
			get
			{
				return this._sAPTradeMarkID;
			}
			set
			{
				this._sAPTradeMarkID = value;
			}
		}
		
		private DateTime? _lastModified;
		public virtual DateTime? LastModified
		{
			get
			{
				return this._lastModified;
			}
			set
			{
				this._lastModified = value;
			}
		}
		
		private int? _changeTrackNumber;
		public virtual int? ChangeTrackNumber
		{
			get
			{
				return this._changeTrackNumber;
			}
			set
			{
				this._changeTrackNumber = value;
			}
		}
		
		private DateTime _rMStatusSetDate;
		public virtual DateTime RMStatusSetDate
		{
			get
			{
				return this._rMStatusSetDate;
			}
			set
			{
				this._rMStatusSetDate = value;
			}
		}
		
		private int? _productLineID;
		public virtual int? ProductLineID
		{
			get
			{
				return this._productLineID;
			}
			set
			{
				this._productLineID = value;
			}
		}
		
		private bool? _isCapstone;
		public virtual bool? IsCapstone
		{
			get
			{
				return this._isCapstone;
			}
			set
			{
				this._isCapstone = value;
			}
		}
		
		private bool _activeInRM;
		public virtual bool ActiveInRM
		{
			get
			{
				return this._activeInRM;
			}
			set
			{
				this._activeInRM = value;
			}
		}
		
		private int? _imageID;
		public virtual int? ImageID
		{
			get
			{
				return this._imageID;
			}
			set
			{
				this._imageID = value;
			}
		}
		
		private IList<PBBrand> _pBBrands = new List<PBBrand>();
		public virtual IList<PBBrand> PBBrands
		{
			get
			{
				return this._pBBrands;
			}
		}
		
		private IList<PBCustomCategory> _pBCustomCategories = new List<PBCustomCategory>();
		public virtual IList<PBCustomCategory> PBCustomCategories
		{
			get
			{
				return this._pBCustomCategories;
			}
		}
		
	}
}
#pragma warning restore 1591
