#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBUserAccount
	{
		private int _gSN;
		public virtual int GSN
		{
			get
			{
				return this._gSN;
			}
			set
			{
				this._gSN = value;
			}
		}
		
		private int _nationalChainID;
		public virtual int NationalChainID
		{
			get
			{
				return this._nationalChainID;
			}
			set
			{
				this._nationalChainID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
