#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBUserPreference
	{
		private string _gSN;
		public virtual string GSN
		{
			get
			{
				return this._gSN;
			}
			set
			{
				this._gSN = value;
			}
		}
		
		private string _nationalAccounts;
		public virtual string NationalAccounts
		{
			get
			{
				return this._nationalAccounts;
			}
			set
			{
				this._nationalAccounts = value;
			}
		}
		
		private string _regionalAccounts;
		public virtual string RegionalAccounts
		{
			get
			{
				return this._regionalAccounts;
			}
			set
			{
				this._regionalAccounts = value;
			}
		}
		
		private string _localAccounts;
		public virtual string LocalAccounts
		{
			get
			{
				return this._localAccounts;
			}
			set
			{
				this._localAccounts = value;
			}
		}
		
		private string _businessUnits;
		public virtual string BusinessUnits
		{
			get
			{
				return this._businessUnits;
			}
			set
			{
				this._businessUnits = value;
			}
		}
		
		private string _regions;
		public virtual string Regions
		{
			get
			{
				return this._regions;
			}
			set
			{
				this._regions = value;
			}
		}
		
		private string _branchs;
		public virtual string Branchs
		{
			get
			{
				return this._branchs;
			}
			set
			{
				this._branchs = value;
			}
		}
		
		private bool _isOverridden;
		public virtual bool IsOverridden
		{
			get
			{
				return this._isOverridden;
			}
			set
			{
				this._isOverridden = value;
			}
		}
		
		private string _area;
		public virtual string Area
		{
			get
			{
				return this._area;
			}
			set
			{
				this._area = value;
			}
		}
		
		private string _superChannel;
		public virtual string SuperChannel
		{
			get
			{
				return this._superChannel;
			}
			set
			{
				this._superChannel = value;
			}
		}
		
		private string _channel;
		public virtual string Channel
		{
			get
			{
				return this._channel;
			}
			set
			{
				this._channel = value;
			}
		}
		
	}
}
#pragma warning restore 1591
