#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class PBVBottlerSalesHier
	{
		private string _zoneName;
		public virtual string ZoneName
		{
			get
			{
				return this._zoneName;
			}
			set
			{
				this._zoneName = value;
			}
		}
		
		private int _zoneID;
		public virtual int ZoneID
		{
			get
			{
				return this._zoneID;
			}
			set
			{
				this._zoneID = value;
			}
		}
		
		private string _totalCompanyName;
		public virtual string TotalCompanyName
		{
			get
			{
				return this._totalCompanyName;
			}
			set
			{
				this._totalCompanyName = value;
			}
		}
		
		private int _totalCompanyID;
		public virtual int TotalCompanyID
		{
			get
			{
				return this._totalCompanyID;
			}
			set
			{
				this._totalCompanyID = value;
			}
		}
		
		private string _systemName;
		public virtual string SystemName
		{
			get
			{
				return this._systemName;
			}
			set
			{
				this._systemName = value;
			}
		}
		
		private int _systemID;
		public virtual int SystemID
		{
			get
			{
				return this._systemID;
			}
			set
			{
				this._systemID = value;
			}
		}
		
		private string _regionName;
		public virtual string RegionName
		{
			get
			{
				return this._regionName;
			}
			set
			{
				this._regionName = value;
			}
		}
		
		private int _regionID;
		public virtual int RegionID
		{
			get
			{
				return this._regionID;
			}
			set
			{
				this._regionID = value;
			}
		}
		
		private string _regionBCNodeID;
		public virtual string RegionBCNodeID
		{
			get
			{
				return this._regionBCNodeID;
			}
			set
			{
				this._regionBCNodeID = value;
			}
		}
		
		private string _hierType;
		public virtual string HierType
		{
			get
			{
				return this._hierType;
			}
			set
			{
				this._hierType = value;
			}
		}
		
		private string _divisionName;
		public virtual string DivisionName
		{
			get
			{
				return this._divisionName;
			}
			set
			{
				this._divisionName = value;
			}
		}
		
		private int _divisionID;
		public virtual int DivisionID
		{
			get
			{
				return this._divisionID;
			}
			set
			{
				this._divisionID = value;
			}
		}
		
		private string _countryName;
		public virtual string CountryName
		{
			get
			{
				return this._countryName;
			}
			set
			{
				this._countryName = value;
			}
		}
		
		private int _countryID;
		public virtual int CountryID
		{
			get
			{
				return this._countryID;
			}
			set
			{
				this._countryID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
