#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class Plant
	{
		private int _plantID;
		public virtual int PlantID
		{
			get
			{
				return this._plantID;
			}
			set
			{
				this._plantID = value;
			}
		}
		
		private int _plantSK;
		public virtual int PlantSK
		{
			get
			{
				return this._plantSK;
			}
			set
			{
				this._plantSK = value;
			}
		}
		
		private string _sAPPlantNumber;
		public virtual string SAPPlantNumber
		{
			get
			{
				return this._sAPPlantNumber;
			}
			set
			{
				this._sAPPlantNumber = value;
			}
		}
		
		private string _sAPSource;
		public virtual string SAPSource
		{
			get
			{
				return this._sAPSource;
			}
			set
			{
				this._sAPSource = value;
			}
		}
		
		private string _plantName;
		public virtual string PlantName
		{
			get
			{
				return this._plantName;
			}
			set
			{
				this._plantName = value;
			}
		}
		
		private string _plantDesc;
		public virtual string PlantDesc
		{
			get
			{
				return this._plantDesc;
			}
			set
			{
				this._plantDesc = value;
			}
		}
		
		private int _regionID;
		public virtual int RegionID
		{
			get
			{
				return this._regionID;
			}
			set
			{
				this._regionID = value;
			}
		}
		
		private int _plantTypeID;
		public virtual int PlantTypeID
		{
			get
			{
				return this._plantTypeID;
			}
			set
			{
				this._plantTypeID = value;
			}
		}
		
		private int _changeTrackNumber;
		public virtual int ChangeTrackNumber
		{
			get
			{
				return this._changeTrackNumber;
			}
			set
			{
				this._changeTrackNumber = value;
			}
		}
		
		private DateTime _lastModified;
		public virtual DateTime LastModified
		{
			get
			{
				return this._lastModified;
			}
			set
			{
				this._lastModified = value;
			}
		}
		
		private decimal? _logitude;
		public virtual decimal? Logitude
		{
			get
			{
				return this._logitude;
			}
			set
			{
				this._logitude = value;
			}
		}
		
		private decimal? _latitude;
		public virtual decimal? Latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				this._latitude = value;
			}
		}
		
		private string _plantManagerGSN;
		public virtual string PlantManagerGSN
		{
			get
			{
				return this._plantManagerGSN;
			}
			set
			{
				this._plantManagerGSN = value;
			}
		}
		
		private string _plantRTM;
		public virtual string PlantRTM
		{
			get
			{
				return this._plantRTM;
			}
			set
			{
				this._plantRTM = value;
			}
		}
		
		private bool? _active;
		public virtual bool? Active
		{
			get
			{
				return this._active;
			}
			set
			{
				this._active = value;
			}
		}
		
	}
}
#pragma warning restore 1591
