#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class SPUserProfile
	{
		private string _gSN;
		public virtual string GSN
		{
			get
			{
				return this._gSN;
			}
			set
			{
				this._gSN = value;
			}
		}
		
		private string _primaryBranch;
		public virtual string PrimaryBranch
		{
			get
			{
				return this._primaryBranch;
			}
			set
			{
				this._primaryBranch = value;
			}
		}
		
		private string _primaryRole;
		public virtual string PrimaryRole
		{
			get
			{
				return this._primaryRole;
			}
			set
			{
				this._primaryRole = value;
			}
		}
		
		private string _additionalBranch;
		public virtual string AdditionalBranch
		{
			get
			{
				return this._additionalBranch;
			}
			set
			{
				this._additionalBranch = value;
			}
		}
		
		private string _branchTradeMark;
		public virtual string BranchTradeMark
		{
			get
			{
				return this._branchTradeMark;
			}
			set
			{
				this._branchTradeMark = value;
			}
		}
		
		private int? _roleID;
		public virtual int? RoleID
		{
			get
			{
				return this._roleID;
			}
			set
			{
				this._roleID = value;
			}
		}
		
		private string _branchCAN;
		public virtual string BranchCAN
		{
			get
			{
				return this._branchCAN;
			}
			set
			{
				this._branchCAN = value;
			}
		}
		
		private bool? _updatedInSP;
		public virtual bool? UpdatedInSP
		{
			get
			{
				return this._updatedInSP;
			}
			set
			{
				this._updatedInSP = value;
			}
		}
		
		private DateTime? _lastLoginTime;
		public virtual DateTime? LastLoginTime
		{
			get
			{
				return this._lastLoginTime;
			}
			set
			{
				this._lastLoginTime = value;
			}
		}
		
		private string _geoRelevancy;
		public virtual string GeoRelevancy
		{
			get
			{
				return this._geoRelevancy;
			}
			set
			{
				this._geoRelevancy = value;
			}
		}
		
		private string _nationalAccount;
		public virtual string NationalAccount
		{
			get
			{
				return this._nationalAccount;
			}
			set
			{
				this._nationalAccount = value;
			}
		}
		
		private string _regionalAccount;
		public virtual string RegionalAccount
		{
			get
			{
				return this._regionalAccount;
			}
			set
			{
				this._regionalAccount = value;
			}
		}
		
		private string _localAccount;
		public virtual string LocalAccount
		{
			get
			{
				return this._localAccount;
			}
			set
			{
				this._localAccount = value;
			}
		}
		
		private string _bU;
		public virtual string BU
		{
			get
			{
				return this._bU;
			}
			set
			{
				this._bU = value;
			}
		}
		
		private string _region;
		public virtual string Region
		{
			get
			{
				return this._region;
			}
			set
			{
				this._region = value;
			}
		}
		
		private string _branch;
		public virtual string Branch
		{
			get
			{
				return this._branch;
			}
			set
			{
				this._branch = value;
			}
		}
		
		private string _area;
		public virtual string Area
		{
			get
			{
				return this._area;
			}
			set
			{
				this._area = value;
			}
		}
		
		private string _superChannel;
		public virtual string SuperChannel
		{
			get
			{
				return this._superChannel;
			}
			set
			{
				this._superChannel = value;
			}
		}
		
		private string _channel;
		public virtual string Channel
		{
			get
			{
				return this._channel;
			}
			set
			{
				this._channel = value;
			}
		}
		
		private int? _primaryBranchId;
		public virtual int? PrimaryBranchId
		{
			get
			{
				return this._primaryBranchId;
			}
			set
			{
				this._primaryBranchId = value;
			}
		}
		
		private string _route;
		public virtual string Route
		{
			get
			{
				return this._route;
			}
			set
			{
				this._route = value;
			}
		}
		
		private string _defaultSystem;
		public virtual string DefaultSystem
		{
			get
			{
				return this._defaultSystem;
			}
			set
			{
				this._defaultSystem = value;
			}
		}
		
		private DateTime? _programLastLoginTime;
		public virtual DateTime? ProgramLastLoginTime
		{
			get
			{
				return this._programLastLoginTime;
			}
			set
			{
				this._programLastLoginTime = value;
			}
		}
		
		private string _goalAccount;
		public virtual string GoalAccount
		{
			get
			{
				return this._goalAccount;
			}
			set
			{
				this._goalAccount = value;
			}
		}
		
		private string _defaultPromotion;
		public virtual string DefaultPromotion
		{
			get
			{
				return this._defaultPromotion;
			}
			set
			{
				this._defaultPromotion = value;
			}
		}
		
		private bool? _isPreferenceSaved;
		public virtual bool? IsPreferenceSaved
		{
			get
			{
				return this._isPreferenceSaved;
			}
			set
			{
				this._isPreferenceSaved = value;
			}
		}
		
		private string _system;
		public virtual string System
		{
			get
			{
				return this._system;
			}
			set
			{
				this._system = value;
			}
		}
		
		private string _zone;
		public virtual string Zone
		{
			get
			{
				return this._zone;
			}
			set
			{
				this._zone = value;
			}
		}
		
		private string _division;
		public virtual string Division
		{
			get
			{
				return this._division;
			}
			set
			{
				this._division = value;
			}
		}
		
		private string _bCRegion;
		public virtual string BCRegion
		{
			get
			{
				return this._bCRegion;
			}
			set
			{
				this._bCRegion = value;
			}
		}
		
		private string _primaryBCRegion;
		public virtual string PrimaryBCRegion
		{
			get
			{
				return this._primaryBCRegion;
			}
			set
			{
				this._primaryBCRegion = value;
			}
		}
		
		private int? _primaryBCRegionID;
		public virtual int? PrimaryBCRegionID
		{
			get
			{
				return this._primaryBCRegionID;
			}
			set
			{
				this._primaryBCRegionID = value;
			}
		}
		
		private string _additionalBCRegion;
		public virtual string AdditionalBCRegion
		{
			get
			{
				return this._additionalBCRegion;
			}
			set
			{
				this._additionalBCRegion = value;
			}
		}
		
		private int _sPUserProfileID;
		public virtual int SPUserProfileID
		{
			get
			{
				return this._sPUserProfileID;
			}
			set
			{
				this._sPUserProfileID = value;
			}
		}
		
		private int? _personaID;
		public virtual int? PersonaID
		{
			get
			{
				return this._personaID;
			}
			set
			{
				this._personaID = value;
			}
		}
		
		private string _plants;
		public virtual string Plants
		{
			get
			{
				return this._plants;
			}
			set
			{
				this._plants = value;
			}
		}
		
		private string _defaultManufacture;
		public virtual string DefaultManufacture
		{
			get
			{
				return this._defaultManufacture;
			}
			set
			{
				this._defaultManufacture = value;
			}
		}
		
		private string _tradeMarkName;
		public virtual string TradeMarkName
		{
			get
			{
				return this._tradeMarkName;
			}
			set
			{
				this._tradeMarkName = value;
			}
		}
		
		private string _productLineName;
		public virtual string ProductLineName
		{
			get
			{
				return this._productLineName;
			}
			set
			{
				this._productLineName = value;
			}
		}
		
		private string _defaultInventoryPref;
		public virtual string DefaultInventoryPref
		{
			get
			{
				return this._defaultInventoryPref;
			}
			set
			{
				this._defaultInventoryPref = value;
			}
		}
		
	}
}
#pragma warning restore 1591
