#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class TransMTDDay
	{
		private DateTime _mTDDayDate;
		public virtual DateTime MTDDayDate
		{
			get
			{
				return this._mTDDayDate;
			}
			set
			{
				this._mTDDayDate = value;
			}
		}
		
		private DateTime _dayDate;
		public virtual DateTime DayDate
		{
			get
			{
				return this._dayDate;
			}
			set
			{
				this._dayDate = value;
			}
		}
		
	}
}
#pragma warning restore 1591
