#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class UserProductLine
	{
		private int _userProductLineID;
		public virtual int UserProductLineID
		{
			get
			{
				return this._userProductLineID;
			}
			set
			{
				this._userProductLineID = value;
			}
		}
		
		private string _gSN;
		public virtual string GSN
		{
			get
			{
				return this._gSN;
			}
			set
			{
				this._gSN = value;
			}
		}
		
		private int? _sPUserProfileID;
		public virtual int? SPUserProfileID
		{
			get
			{
				return this._sPUserProfileID;
			}
			set
			{
				this._sPUserProfileID = value;
			}
		}
		
		private int? _productLineID;
		public virtual int? ProductLineID
		{
			get
			{
				return this._productLineID;
			}
			set
			{
				this._productLineID = value;
			}
		}
		
		private int? _tradeMarkID;
		public virtual int? TradeMarkID
		{
			get
			{
				return this._tradeMarkID;
			}
			set
			{
				this._tradeMarkID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
