#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class UserPersona
	{
		private int? _portalRoleID;
		public virtual int? PortalRoleID
		{
			get
			{
				return this._portalRoleID;
			}
			set
			{
				this._portalRoleID = value;
			}
		}
		
		private int? _personaID;
		public virtual int? PersonaID
		{
			get
			{
				return this._personaID;
			}
			set
			{
				this._personaID = value;
			}
		}
		
		private int? _precedence;
		public virtual int? Precedence
		{
			get
			{
				return this._precedence;
			}
			set
			{
				this._precedence = value;
			}
		}
		
		private string _portalRoleName;
		public virtual string PortalRoleName
		{
			get
			{
				return this._portalRoleName;
			}
			set
			{
				this._portalRoleName = value;
			}
		}
		
		private string _personaName;
		public virtual string PersonaName
		{
			get
			{
				return this._personaName;
			}
			set
			{
				this._personaName = value;
			}
		}
		
		private string _portalShortName;
		public virtual string PortalShortName
		{
			get
			{
				return this._portalShortName;
			}
			set
			{
				this._portalShortName = value;
			}
		}
		
	}
}
#pragma warning restore 1591
