#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DPSG.Portal.Framework.SDM;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class UserBranchTradeMark
	{
		private int _userInBranchID;
		public virtual int UserInBranchID
		{
			get
			{
				return this._userInBranchID;
			}
			set
			{
				this._userInBranchID = value;
			}
		}
		
		private int _userBranchTradeMarkID;
		public virtual int UserBranchTradeMarkID
		{
			get
			{
				return this._userBranchTradeMarkID;
			}
			set
			{
				this._userBranchTradeMarkID = value;
			}
		}
		
		private int _tradeMarkID;
		public virtual int TradeMarkID
		{
			get
			{
				return this._tradeMarkID;
			}
			set
			{
				this._tradeMarkID = value;
			}
		}
		
		private UserInBranch _userInBranch;
		public virtual UserInBranch UserInBranch
		{
			get
			{
				return this._userInBranch;
			}
			set
			{
				this._userInBranch = value;
			}
		}
		
	}
}
#pragma warning restore 1591
