#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DPSG.Portal.Framework.SDM	
{
	public partial class UserLocation
	{
		private int _userLocationID;
		public virtual int UserLocationID
		{
			get
			{
				return this._userLocationID;
			}
			set
			{
				this._userLocationID = value;
			}
		}
		
		private string _gSN;
		public virtual string GSN
		{
			get
			{
				return this._gSN;
			}
			set
			{
				this._gSN = value;
			}
		}
		
		private int? _bUID;
		public virtual int? BUID
		{
			get
			{
				return this._bUID;
			}
			set
			{
				this._bUID = value;
			}
		}
		
		private int? _regionID;
		public virtual int? RegionID
		{
			get
			{
				return this._regionID;
			}
			set
			{
				this._regionID = value;
			}
		}
		
		private int? _branchID;
		public virtual int? BranchID
		{
			get
			{
				return this._branchID;
			}
			set
			{
				this._branchID = value;
			}
		}
		
		private int? _areaID;
		public virtual int? AreaID
		{
			get
			{
				return this._areaID;
			}
			set
			{
				this._areaID = value;
			}
		}
		
		private int? _systemID;
		public virtual int? SystemID
		{
			get
			{
				return this._systemID;
			}
			set
			{
				this._systemID = value;
			}
		}
		
		private int? _zoneID;
		public virtual int? ZoneID
		{
			get
			{
				return this._zoneID;
			}
			set
			{
				this._zoneID = value;
			}
		}
		
		private int? _divisionID;
		public virtual int? DivisionID
		{
			get
			{
				return this._divisionID;
			}
			set
			{
				this._divisionID = value;
			}
		}
		
		private int? _bCRegionID;
		public virtual int? BCRegionID
		{
			get
			{
				return this._bCRegionID;
			}
			set
			{
				this._bCRegionID = value;
			}
		}
		
		private bool? _isReadOnly;
		public virtual bool? IsReadOnly
		{
			get
			{
				return this._isReadOnly;
			}
			set
			{
				this._isReadOnly = value;
			}
		}
		
		private int? _sPUserProfileID;
		public virtual int? SPUserProfileID
		{
			get
			{
				return this._sPUserProfileID;
			}
			set
			{
				this._sPUserProfileID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
