//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPSG.DSDDeliveryTime.WebAPI.DataService2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public System.DateTime DeliveryDate { get; set; }
        public string RouteNumber { get; set; }
        public int SalesOfficeID { get; set; }
        public string DriverID { get; set; }
        public string StopType { get; set; }
        public long StopID { get; set; }
        public int StopSequence { get; set; }
        public System.DateTime PlannedArrivalTimeUTC { get; set; }
        public Nullable<int> PlannedServiceTimeInSec { get; set; }
        public Nullable<System.DateTime> ActualArrivalTime { get; set; }
        public string ActualArrivalTimeZone { get; set; }
        public Nullable<System.DateTime> ActualDepartureTime { get; set; }
        public string ActualDepartureTimeZone { get; set; }
        public Nullable<System.DateTime> EstimatedArrivalTime { get; set; }
        public string EstimatedArrivalTimeZone { get; set; }
        public Nullable<System.DateTime> LastUpdatedTimeUTC { get; set; }
        public string LastUpdatedBy { get; set; }
        public string LastUpdatedDriverID { get; set; }
    }
}
