USE [Portal_Data]
GO

/****** Object:  Table [SAP].[KPI]    Script Date: 3/21/2013 4:59:42 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SAP].[KPI](
	[KPIID] [int] NOT NULL,
	[SAPKPIID] [nvarchar](50) NULL,
	[KPIName] [nvarchar](150) NULL,
 CONSTRAINT [PK_KPI] PRIMARY KEY CLUSTERED 
(
	[KPIID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


