USE [Portal_Data]
GO

/****** Object:  Table [SAP].[Flavor]    Script Date: 3/21/2013 4:57:57 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SAP].[Flavor](
	[FlavorID] [int] IDENTITY(1,1) NOT NULL,
	[SAPFlavorID] [varchar](50) NOT NULL,
	[FlavorName] [varchar](128) NOT NULL,
 CONSTRAINT [PK_Flavor] PRIMARY KEY CLUSTERED 
(
	[FlavorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


