USE [Portal_Data]
GO

/****** Object:  Table [SAP].[BusinessUnit]    Script Date: 3/21/2013 4:55:21 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SAP].[BusinessUnit](
	[BUID] [int] IDENTITY(1,1) NOT NULL,
	[SAPBUID] [varchar](50) NOT NULL,
	[BUName] [nvarchar](50) NOT NULL,
	[SPBUName] [varchar](50) NULL,
 CONSTRAINT [PK_BusinessUnit] PRIMARY KEY CLUSTERED 
(
	[BUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


