USE [Portal_Data]
GO

/****** Object:  Table [SAP].[TradeMark]    Script Date: 3/21/2013 5:11:58 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [SAP].[TradeMark](
	[TradeMarkID] [int] IDENTITY(1,1) NOT NULL,
	[SAPTradeMarkID] [varchar](50) NOT NULL,
	[TradeMarkName] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_TradeMark] PRIMARY KEY CLUSTERED 
(
	[TradeMarkID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


